export const CITIZEN_USER_PROFILE = {
  name: 'NITHISH',
  phone: '9093214543',
  formattedPhone: '+91 90932 14543',
  address: '11TH STREET, GANDHI NAGAR, TIRUPPUR',
  ward: 'Ward 12, Gandhi Nagar, Tiruppur',
  shortLocation: 'Gandhi Nagar, Tiruppur',
}

export const INITIAL_CITIZEN_ISSUES = [
  {
    id: 'SETU-CIT-1042',
    title: 'Contaminated Water Supply in Block 4',
    category: 'Water Supply',
    status: 'in_progress', // 'submitted' | 'under_review' | 'assigned' | 'in_progress' | 'resolved'
    date: 'Sep 02, 2026',
    location: '11th Street, Gandhi Nagar, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Drinking water pipeline has brown discoloration and sediment for the past 4 days affecting over 120 households. Water samples submitted to municipal lab.',
    upvotes: 48,
    isUpvoted: false,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 02, 2026 • 09:30 AM',
        actor: 'Citizen Community',
        note: 'Issue registered with local photographic evidence.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Ward Officer Review',
        date: 'Sep 02, 2026 • 02:15 PM',
        actor: 'Ward 12 Administration',
        note: 'Field verification conducted. High priority alert raised.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Assigned to Water Board',
        date: 'Sep 03, 2026 • 11:00 AM',
        actor: 'Municipal Water Resources',
        note: 'Repair crew and university water testing group dispatched.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Pipe Relining in Progress',
        date: 'Sep 04, 2026 • 03:30 PM',
        actor: 'Engineering Division',
        note: 'Main feeder replacement underway. Temporary water tanker deployed.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Final Quality Clearance',
        date: 'Estimated: Sep 06, 2026',
        actor: 'Health Inspection Team',
        note: 'Awaiting lab water purity certification before closing.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Tap Water Sample',
        caption: 'Brown sediment captured on Sep 2',
        color: '#E07A4E',
      },
      {
        type: 'photo',
        title: 'Pipeline Joint Leak',
        caption: 'Seepage near crossroad junction',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-CIT-1038',
    title: 'Deep Potholes and Waterlogging at Market Junction',
    category: 'Road Infrastructure',
    status: 'resolved',
    date: 'Aug 26, 2026',
    location: 'Main Market Road, Gandhi Nagar, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Severe potholes causing traffic jams and two-wheeler skidding during evening rains. High pedestrian footfall area.',
    upvotes: 84,
    isUpvoted: true,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Aug 26, 2026 • 10:00 AM',
        actor: 'Market Traders Association',
        note: 'Multiple resident signatures attached.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Public Works Verification',
        date: 'Aug 26, 2026 • 04:00 PM',
        actor: 'Ward Inspector',
        note: 'Inspected and classified under Urgent Road Safety.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Sanction Approved',
        date: 'Aug 27, 2026 • 01:30 PM',
        actor: 'Municipal Corporation',
        note: 'Asphalt allocation sanctioned.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Resurfacing & Drainage Work',
        date: 'Aug 29, 2026 • 08:00 PM',
        actor: 'Road Maintenance Crew',
        note: 'Potholes filled and drainage gradient restored.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Issue Resolved & Verified',
        date: 'Aug 30, 2026 • 11:00 AM',
        actor: 'Quality Assurance Board',
        note: 'Completed road inspection approved by Ward 12 supervisor.',
        completed: true,
      },
    ],
    resolutionSummary: 'Road resurfacing and drainage clearing completed. Post-work quality verified on Aug 30, 2026.',
    evidence: [
      {
        type: 'photo',
        title: 'Initial Pothole Depth',
        caption: 'Hazard on Market Road junction',
        color: '#E07A4E',
      },
      {
        type: 'photo',
        title: 'Completed Resurfacing',
        caption: 'Restored smooth road surface',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-CIT-1025',
    title: 'Non-functional Streetlights on High School Road',
    category: 'Public Lighting',
    status: 'assigned',
    date: 'Aug 29, 2026',
    location: 'Govt High School Road, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Five consecutive LED street lights are off for a week, creating safety concerns for evening school students and pedestrians.',
    upvotes: 32,
    isUpvoted: false,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Aug 29, 2026 • 07:15 PM',
        actor: 'Parent-Teacher Group',
        note: 'Night time photos submitted.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Electrical Dept Review',
        date: 'Aug 30, 2026 • 11:00 AM',
        actor: 'Ward Electrical Officer',
        note: 'Transformer circuit fault identified.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Assigned to Zone Lineman',
        date: 'Aug 31, 2026 • 09:45 AM',
        actor: 'Electricity Board',
        note: 'Component replacement parts scheduled.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Line Repair & Replacement',
        date: 'Scheduled: Sep 06, 2026',
        actor: 'Zone Electrical Crew',
        note: 'Underground wiring inspection pending.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Restoration Verification',
        date: 'Pending',
        actor: 'Ward 12 Safety Inspector',
        note: 'Night illumination audit will confirm resolution.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Dark Stretch Photo',
        caption: 'School road stretch at 8 PM',
        color: '#1F2A28',
      },
    ],
  },
  {
    id: 'SETU-CIT-1011',
    title: 'Garbage Overflow and Irregular Collection',
    category: 'Sanitation',
    status: 'under_review',
    date: 'Sep 04, 2026',
    location: 'Community Park Corner, Gandhi Nagar, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Secondary waste collection bin overflowing for 3 days attracting stray animals and blocking the pedestrian walkway.',
    upvotes: 19,
    isUpvoted: false,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 04, 2026 • 08:00 AM',
        actor: 'Resident Welfare Group',
        note: 'Geotagged photographic report submitted.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Sanitation Supervisor Review',
        date: 'Sep 04, 2026 • 01:30 PM',
        actor: 'Solid Waste Management',
        note: 'Route inspection assigned to zonal compactor vehicle.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Compactor Vehicle Dispatch',
        date: 'Pending',
        actor: 'Zonal Sanitation Team',
        note: 'Waste clearance scheduled.',
        completed: false,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Bin Clearance & Sanitization',
        date: 'Pending',
        actor: 'Sanitation Division',
        note: 'Clearing and bleaching powder sanitization.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Resolved State',
        date: 'Pending',
        actor: 'Ward Supervisor',
        note: 'Daily collection route check.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Overflowing Bin',
        caption: 'Park corner waste accumulation',
        color: '#E07A4E',
      },
    ],
  },
]
