export const CATEGORIES = [
  'Water Supply',
  'Roads',
  'Electricity',
  'Waste Management',
  'Sanitation',
  'Public Infrastructure',
  'Environment',
  'Other',
]

export const CITIZEN_USER_PROFILE = {
  name: 'NITHISH',
  phone: '9093214543',
  formattedPhone: '+91 90932 14543',
  address: '11TH STREET, GANDHI NAGAR, TIRUPPUR',
  ward: 'Ward 12, Gandhi Nagar, Tiruppur',
  shortLocation: 'Gandhi Nagar, Tiruppur',
}

export const INITIAL_CITIZEN_ISSUES = [
  {
    id: 'SETU-CIT-1042',
    title: 'Contaminated Water Supply in Block 4',
    category: 'Water Supply',
    status: 'in_progress', // 'submitted' | 'under_review' | 'assigned' | 'in_progress' | 'resolved'
    date: 'Sep 02, 2026',
    location: '11th Street, Gandhi Nagar, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Drinking water pipeline has brown discoloration and sediment for the past 4 days affecting over 120 households. Water samples submitted to municipal lab.',
    upvotes: 48,
    isUpvoted: false,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 02, 2026 • 09:30 AM',
        actor: 'Citizen Community',
        note: 'Issue registered with local photographic evidence.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Ward Officer Review',
        date: 'Sep 02, 2026 • 02:15 PM',
        actor: 'Ward 12 Administration',
        note: 'Field verification conducted. High priority alert raised.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Assigned to Water Board',
        date: 'Sep 03, 2026 • 11:00 AM',
        actor: 'Municipal Water Resources',
        note: 'Repair crew and university water testing group dispatched.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Pipe Relining in Progress',
        date: 'Sep 04, 2026 • 03:30 PM',
        actor: 'Engineering Division',
        note: 'Main feeder replacement underway. Temporary water tanker deployed.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Final Quality Clearance',
        date: 'Estimated: Sep 06, 2026',
        actor: 'Health Inspection Team',
        note: 'Awaiting lab water purity certification before closing.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Tap Water Sample',
        caption: 'Brown sediment captured on Sep 2',
        color: '#E07A4E',
      },
      {
        type: 'photo',
        title: 'Pipeline Joint Leak',
        caption: 'Seepage near crossroad junction',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-CIT-1038',
    title: 'Deep Potholes and Waterlogging at Market Junction',
    category: 'Road Infrastructure',
    status: 'resolved',
    date: 'Aug 26, 2026',
    location: 'Main Market Road, Gandhi Nagar, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Severe potholes causing traffic jams and two-wheeler skidding during evening rains. High pedestrian footfall area.',
    upvotes: 84,
    isUpvoted: true,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Aug 26, 2026 • 10:00 AM',
        actor: 'Market Traders Association',
        note: 'Multiple resident signatures attached.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Public Works Verification',
        date: 'Aug 26, 2026 • 04:00 PM',
        actor: 'Ward Inspector',
        note: 'Inspected and classified under Urgent Road Safety.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Sanction Approved',
        date: 'Aug 27, 2026 • 01:30 PM',
        actor: 'Municipal Corporation',
        note: 'Asphalt allocation sanctioned.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Resurfacing & Drainage Work',
        date: 'Aug 29, 2026 • 08:00 PM',
        actor: 'Road Maintenance Crew',
        note: 'Potholes filled and drainage gradient restored.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Issue Resolved & Verified',
        date: 'Aug 30, 2026 • 11:00 AM',
        actor: 'Quality Assurance Board',
        note: 'Completed road inspection approved by Ward 12 supervisor.',
        completed: true,
      },
    ],
    resolutionSummary: 'Road resurfacing and drainage clearing completed. Post-work quality verified on Aug 30, 2026.',
    evidence: [
      {
        type: 'photo',
        title: 'Initial Pothole Depth',
        caption: 'Hazard on Market Road junction',
        color: '#E07A4E',
      },
      {
        type: 'photo',
        title: 'Completed Resurfacing',
        caption: 'Restored smooth road surface',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-CIT-1025',
    title: 'Non-functional Streetlights on High School Road',
    category: 'Public Lighting',
    status: 'assigned',
    date: 'Aug 29, 2026',
    location: 'Govt High School Road, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Five consecutive LED street lights are off for a week, creating safety concerns for evening school students and pedestrians.',
    upvotes: 32,
    isUpvoted: false,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Aug 29, 2026 • 07:15 PM',
        actor: 'Parent-Teacher Group',
        note: 'Night time photos submitted.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Electrical Dept Review',
        date: 'Aug 30, 2026 • 11:00 AM',
        actor: 'Ward Electrical Officer',
        note: 'Transformer circuit fault identified.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Assigned to Zone Lineman',
        date: 'Aug 31, 2026 • 09:45 AM',
        actor: 'Electricity Board',
        note: 'Component replacement parts scheduled.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Line Repair & Replacement',
        date: 'Scheduled: Sep 06, 2026',
        actor: 'Zone Electrical Crew',
        note: 'Underground wiring inspection pending.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Restoration Verification',
        date: 'Pending',
        actor: 'Ward 12 Safety Inspector',
        note: 'Night illumination audit will confirm resolution.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Dark Stretch Photo',
        caption: 'School road stretch at 8 PM',
        color: '#1F2A28',
      },
    ],
  },
  {
    id: 'SETU-CIT-1011',
    title: 'Garbage Overflow and Irregular Collection',
    category: 'Sanitation',
    status: 'under_review',
    date: 'Sep 04, 2026',
    location: 'Community Park Corner, Gandhi Nagar, Tiruppur',
    ward: 'Ward 12, Gandhi Nagar, Tiruppur',
    description: 'Secondary waste collection bin overflowing for 3 days attracting stray animals and blocking the pedestrian walkway.',
    upvotes: 19,
    isUpvoted: false,
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 04, 2026 • 08:00 AM',
        actor: 'Resident Welfare Group',
        note: 'Geotagged photographic report submitted.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Sanitation Supervisor Review',
        date: 'Sep 04, 2026 • 01:30 PM',
        actor: 'Solid Waste Management',
        note: 'Route inspection assigned to zonal compactor vehicle.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Compactor Vehicle Dispatch',
        date: 'Pending',
        actor: 'Zonal Sanitation Team',
        note: 'Waste clearance scheduled.',
        completed: false,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Bin Clearance & Sanitization',
        date: 'Pending',
        actor: 'Sanitation Division',
        note: 'Clearing and bleaching powder sanitization.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Resolved State',
        date: 'Pending',
        actor: 'Ward Supervisor',
        note: 'Daily collection route check.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Overflowing Bin',
        caption: 'Park corner waste accumulation',
        color: '#E07A4E',
      },
    ],
  },
]

export const COMMUNITY_CITIZEN_ISSUES = [
  {
    id: 'SETU-COM-301',
    title: 'Low Pressure & Pipeline Leakage at Rayapuram Main Water Tank',
    category: 'Water Supply',
    status: 'in_progress',
    date: 'Sep 03, 2026',
    location: 'Tank Street, Rayapuram, Tiruppur',
    ward: 'Ward 8, Rayapuram, Tiruppur',
    description: 'Underground pipeline ruptured near distribution valve. Clean drinking water is flowing onto roads while over 200 tenements have zero water pressure.',
    upvotes: 67,
    isUpvoted: false,
    isAnonymous: false,
    submitterName: 'Murugan S.',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 03, 2026 • 08:30 AM',
        actor: 'Rayapuram Resident Council',
        note: 'Reported with GPS tag and leakage video.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Technical Review',
        date: 'Sep 03, 2026 • 01:15 PM',
        actor: 'Ward 8 Water Engineer',
        note: 'Pressure loss confirmed at junction.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Repair Crew Assigned',
        date: 'Sep 04, 2026 • 09:00 AM',
        actor: 'TWAD Board Crew',
        note: 'Replacement valve parts dispatched.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Excavation & Pipe Replacement',
        date: 'Sep 05, 2026 • 02:00 PM',
        actor: 'Maintenance Division',
        note: 'Excavation underway to install reinforced sleeve.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Pressure Restoration',
        date: 'Estimated: Sep 07, 2026',
        actor: 'Inspection Team',
        note: 'Final test run scheduled.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Pipeline Joint Leak',
        caption: 'Water overflowing near distribution valve',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-COM-302',
    title: 'Damaged Pavement and Open Drainage Grate near Old Bus Stand',
    category: 'Roads',
    status: 'under_review',
    date: 'Sep 05, 2026',
    location: 'Old Bus Stand Entry Gate, Tiruppur',
    ward: 'Ward 15, Central Zone, Tiruppur',
    description: 'Broken concrete pavement slab with open drain grate creates severe hazard for commuters, elderly citizens, and school children catching buses.',
    upvotes: 52,
    isUpvoted: false,
    isAnonymous: false,
    submitterName: 'Kavitha R.',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 05, 2026 • 09:15 AM',
        actor: 'Commuters Association',
        note: 'Civic safety complaint registered.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Public Works Verification',
        date: 'Sep 05, 2026 • 03:00 PM',
        actor: 'Highways & Footpaths Wing',
        note: 'Inspection site visit logged.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Civil Contractor Assignment',
        date: 'Pending',
        actor: 'Municipal Corporation',
        note: 'Cast-iron grate replacement order placed.',
        completed: false,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Slab Casting & Grate Installation',
        date: 'Pending',
        actor: 'PW Maintenance Crew',
        note: 'On-site installation scheduled.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Footpath Clearance',
        date: 'Pending',
        actor: 'Safety Inspector',
        note: 'Pedestrian access certification.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Damaged Footpath Slab',
        caption: 'Uncovered drain gap at bus stop curb',
        color: '#E07A4E',
      },
    ],
  },
  {
    id: 'SETU-COM-303',
    title: 'Exposed Overhead Power Cable Hanging Low near Children\'s Park',
    category: 'Electricity',
    status: 'assigned',
    date: 'Sep 04, 2026',
    location: 'VOC Nagar 3rd Cross, Tiruppur',
    ward: 'Ward 21, VOC Nagar, Tiruppur',
    description: 'High voltage service cable snapped from bracket and hanging barely 6 feet above pedestrian pathway right next to children playground swings.',
    upvotes: 91,
    isUpvoted: false,
    isAnonymous: true,
    submitterName: 'Anonymous Citizen',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Emergency Issue Submitted',
        date: 'Sep 04, 2026 • 07:45 AM',
        actor: 'Anonymous Citizen',
        note: 'Immediate hazard flag raised.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'TANGEDCO Safety Alert',
        date: 'Sep 04, 2026 • 08:30 AM',
        actor: 'Zone Electrical Inspector',
        note: 'Urgent priority classification.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Emergency Line Team Dispatched',
        date: 'Sep 04, 2026 • 10:00 AM',
        actor: 'Electricity Distribution Team',
        note: 'Linemen assigned with aerial hoist vehicle.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Re-tensioning & Insulator Upgrade',
        date: 'Scheduled: Sep 06, 2026',
        actor: 'Line Maintenance Crew',
        note: 'Overhead bracket replacement.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Electrical Safety Clearance',
        date: 'Pending',
        actor: 'Safety Auditor',
        note: 'Height clearance verification.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Low Hanging Cable',
        caption: 'Overhead cable sagging across pathway',
        color: '#1F2A28',
      },
    ],
  },
  {
    id: 'SETU-COM-304',
    title: 'Irregular Door-to-Door Waste Collection in Postal Colony',
    category: 'Waste Management',
    status: 'in_progress',
    date: 'Sep 01, 2026',
    location: 'Postal Colony Main Road, Tiruppur',
    ward: 'Ward 14, Postal Colony, Tiruppur',
    description: 'Municipal battery vehicles have missed scheduled door-to-door green/blue bin waste collection for 5 consecutive days, causing residents to dump bags at street corners.',
    upvotes: 38,
    isUpvoted: false,
    isAnonymous: false,
    submitterName: 'Priya Venkatesh',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 01, 2026 • 10:00 AM',
        actor: 'Postal Colony Residents Welfare',
        note: 'Multiple resident signatures attached.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Sanitation Officer Review',
        date: 'Sep 01, 2026 • 03:45 PM',
        actor: 'Ward 14 Sanitation Inspector',
        note: 'Vehicle route breakdown identified.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Relief Vehicle Route Rerouted',
        date: 'Sep 02, 2026 • 09:30 AM',
        actor: 'Solid Waste Management',
        note: 'Backup EV compactor assigned to morning shift.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Special Waste Clearance Drive',
        date: 'Sep 03, 2026 • 07:00 AM',
        actor: 'Sanitation Division',
        note: 'Accumulated corner waste cleared and sanitized.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Daily Schedule Monitoring',
        date: 'Estimated: Sep 07, 2026',
        actor: 'Ward Supervisor',
        note: 'Ensuring daily consistency before closing.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Street Corner Waste',
        caption: 'Accumulated garbage near residential gate',
        color: '#E07A4E',
      },
    ],
  },
  {
    id: 'SETU-COM-305',
    title: 'Stagnant Stormwater and Heavy Mosquito Breeding in Low-lying Area',
    category: 'Sanitation',
    status: 'submitted',
    date: 'Sep 05, 2026',
    location: 'Periyar Nagar 4th Street, Tiruppur',
    ward: 'Ward 19, Periyar Nagar, Tiruppur',
    description: 'Post-rain water remains trapped in unfilled vacant plots without drainage outlets. Foul odor and intense mosquito infestation causing fever cases in neighboring houses.',
    upvotes: 44,
    isUpvoted: false,
    isAnonymous: true,
    submitterName: 'Anonymous Citizen',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Sep 05, 2026 • 11:30 AM',
        actor: 'Anonymous Citizen',
        note: 'Vector-borne illness risk reported.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Public Health Department Queue',
        date: 'Pending',
        actor: 'City Health Officer',
        note: 'Awaiting field inspector verification.',
        completed: false,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Fogging & Dewatering Assignment',
        date: 'Pending',
        actor: 'Vector Control Team',
        note: 'Mobile suction pump scheduling.',
        completed: false,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Anti-larval Spraying',
        date: 'Pending',
        actor: 'Sanitation Team',
        note: 'Spraying of bio-larvicides and earth-moving channel work.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Drainage Restoration',
        date: 'Pending',
        actor: 'Health Officer',
        note: 'Post-fogging safety check.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Stagnant Water Plot',
        caption: 'Green stagnant water near residential dwellings',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-COM-306',
    title: 'Broken Shade Canopy and Seating at Municipal Health Sub-centre',
    category: 'Public Infrastructure',
    status: 'resolved',
    date: 'Aug 24, 2026',
    location: 'KPN Colony Municipal Clinic, Tiruppur',
    ward: 'Ward 11, KPN Colony, Tiruppur',
    description: 'Patients including pregnant mothers and senior citizens were forced to wait in direct scorching sun due to collapsed tin awning and rusted iron benches.',
    upvotes: 79,
    isUpvoted: true,
    isAnonymous: false,
    submitterName: 'R. Selvam',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Issue Submitted',
        date: 'Aug 24, 2026 • 09:00 AM',
        actor: 'Clinic Visiting Committee',
        note: 'Photographs of damaged shelter attached.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Infrastructure Wing Inspection',
        date: 'Aug 24, 2026 • 02:00 PM',
        actor: 'Ward 11 Junior Engineer',
        note: 'Structure replacement sanctioned.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Fabrication Work Approved',
        date: 'Aug 25, 2026 • 11:30 AM',
        actor: 'Municipal Building Works',
        note: 'All-weather polycarbonate roofing ordered.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'New Shed & Seating Erected',
        date: 'Aug 28, 2026 • 05:00 PM',
        actor: 'Contractor Team',
        note: 'Polycarbonate shelter and 16 stainless steel seats installed.',
        completed: true,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Inspection & Sign-off',
        date: 'Aug 29, 2026 • 10:30 AM',
        actor: 'Medical Officer & Ward Supervisor',
        note: 'Completed shelter verified and opened for public use.',
        completed: true,
      },
    ],
    resolutionSummary: 'Brand new weatherproof polycarbonate canopy and 16 stainless steel chairs installed at the health centre entrance.',
    evidence: [
      {
        type: 'photo',
        title: 'Damaged Canopy',
        caption: 'Broken awning before repair',
        color: '#E07A4E',
      },
      {
        type: 'photo',
        title: 'Completed Canopy',
        caption: 'Restored shelter with modern seating',
        color: '#176B5B',
      },
    ],
  },
  {
    id: 'SETU-COM-307',
    title: 'Untreated Industrial Dyeing Effluent Dumping into Noyyal Canal',
    category: 'Environment',
    status: 'under_review',
    date: 'Sep 04, 2026',
    location: 'Kasipalayam Canal Bridge, Tiruppur',
    ward: 'Ward 24, Kasipalayam, Tiruppur',
    description: 'Dark purple colored industrial effluent with chemical odor discharged during midnight hours into public rainwater canal connecting to Noyyal river.',
    upvotes: 114,
    isUpvoted: false,
    isAnonymous: false,
    submitterName: 'Green Tiruppur Forum',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Critical Environmental Alert',
        date: 'Sep 04, 2026 • 06:15 AM',
        actor: 'Green Tiruppur Environmental NGO',
        note: 'Water sample pH test data and discharge photos uploaded.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Pollution Control Board Joint Inspection',
        date: 'Sep 04, 2026 • 02:00 PM',
        actor: 'TNPCB Tiruppur South Division',
        note: 'Official water samples collected for spectrophotometer testing.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Enforcement Notice Preparation',
        date: 'Pending',
        actor: 'Environmental Vigilance Team',
        note: 'Tracing unauthorized pipeline connections.',
        completed: false,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Sealing of Illegal Outlets',
        date: 'Pending',
        actor: 'Joint Revenue & PCB Team',
        note: 'Plugging unauthorized discharge points.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Water Purity Re-audit',
        date: 'Pending',
        actor: 'District Environmental Committee',
        note: 'Verification of zero-liquid discharge compliance.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Colored Effluent Discharge',
        caption: 'Chemical seepage captured at culvert',
        color: '#E07A4E',
      },
    ],
  },
  {
    id: 'SETU-COM-308',
    title: 'Missing Street Signboards and Convex Safety Mirror at Blind Curve',
    category: 'Other',
    status: 'assigned',
    date: 'Aug 30, 2026',
    location: 'Avinashi Road Link Cross, Tiruppur',
    ward: 'Ward 5, Northern Zone, Tiruppur',
    description: 'Blind corner turn near bridge lacks road safety signage and convex mirror, leading to frequent near-miss collisions during heavy morning textile truck traffic.',
    upvotes: 26,
    isUpvoted: false,
    isAnonymous: true,
    submitterName: 'Anonymous Citizen',
    timeline: [
      {
        step: 'submitted',
        labelKey: 'status.submitted',
        title: 'Road Safety Issue Submitted',
        date: 'Aug 30, 2026 • 04:00 PM',
        actor: 'Anonymous Citizen',
        note: 'Location GPS coordinates and traffic flow notes included.',
        completed: true,
      },
      {
        step: 'under_review',
        labelKey: 'status.underReview',
        title: 'Traffic Police & PWD Assessment',
        date: 'Aug 31, 2026 • 11:30 AM',
        actor: 'Traffic Wing Sub-Inspector',
        note: 'Black spot verified for safety retrofitting.',
        completed: true,
      },
      {
        step: 'assigned',
        labelKey: 'status.assigned',
        title: 'Mirror & Signpost Installation Order',
        date: 'Sep 02, 2026 • 10:00 AM',
        actor: 'Highways Safety Engineering',
        note: '1000mm outdoor convex mirror and reflective warning boards allotted.',
        completed: true,
      },
      {
        step: 'action_taken',
        labelKey: 'status.actionTaken',
        title: 'Pole Erection & Alignment',
        date: 'Scheduled: Sep 08, 2026',
        actor: 'Signage Maintenance Crew',
        note: 'Foundation grouting work.',
        completed: false,
      },
      {
        step: 'resolved',
        labelKey: 'status.resolved',
        title: 'Road Safety Audit',
        date: 'Pending',
        actor: 'Traffic Inspector',
        note: 'Visibility angle check.',
        completed: false,
      },
    ],
    evidence: [
      {
        type: 'photo',
        title: 'Blind Turn Corner',
        caption: 'Sharp blind turn on busy link stretch',
        color: '#1F2A28',
      },
    ],
  },
]

