/**
 * SETU University Dashboards - Comprehensive API-Ready Mock Dataset
 * Contains multi-university domains (Engineering, Law, Medicine, Agriculture, Yoga/Ayurveda),
 * government research challenges, team states (1 mentor + up to 5 students),
 * approval requests, contributions, notifications, and time-based metrics.
 */

export const DASHBOARD_UNIVERSITIES = [
  { id: 'u1', name: 'Anna University, Chennai', state: 'Tamil Nadu', code: 'AU-CHE', type: 'Engineering & Technology', chancellor: 'Dr. R. Velraj' },
  { id: 'u2', name: 'Indian Institute of Technology Madras (IIT Madras)', state: 'Tamil Nadu', code: 'IIT-M', type: 'Engineering & Advanced Science', chancellor: 'Prof. V. Kamakoti' },
  { id: 'u12', name: 'Tamil Nadu Agricultural University (TNAU), Coimbatore', state: 'Tamil Nadu', code: 'TNAU-CBE', type: 'Agriculture & Life Sciences', chancellor: 'Dr. V. Geethalakshmi' },
  { id: 'u13', name: 'Madras Medical College (MMC), Chennai', state: 'Tamil Nadu', code: 'MMC-CHE', type: 'Medical & Healthcare Sciences', chancellor: 'Dr. E. Theranirajan' },
  { id: 'u14', name: 'National Law School of India University (NLSIU), Bengaluru', state: 'Karnataka', code: 'NLSIU-BLR', type: 'Law & Public Policy', chancellor: 'Prof. Sudhir Krishnaswamy' },
  { id: 'u15', name: 'S-VYASA Yoga University, Bengaluru', state: 'Karnataka', code: 'SVYASA-BLR', type: 'Yoga & Integrative Health', chancellor: 'Dr. H. R. Nagendra' },
]

export const DASHBOARD_DEPARTMENTS = [
  { id: 'dept-civ', code: 'CIV-ENV', name: 'Civil & Environmental Engineering', universityId: 'u2' },
  { id: 'dept-cse', code: 'CSE-DS', name: 'Computer Science & Engineering (AI/Data)', universityId: 'u1' },
  { id: 'dept-eee', code: 'EEE-RES', name: 'Electrical & Renewable Energy Systems', universityId: 'u1' },
  { id: 'dept-agr', code: 'AGR-SOIL', name: 'Agronomy, Soil Science & Water Management', universityId: 'u12' },
  { id: 'dept-med', code: 'MED-PUB', name: 'Public Health & Community Epidemiology', universityId: 'u13' },
  { id: 'dept-law', code: 'LAW-CYB', name: 'Cyber Law, Data Governance & Public Policy', universityId: 'u14' },
  { id: 'dept-yog', code: 'YOG-INT', name: 'Integrative Medicine & Yoga Sciences', universityId: 'u15' },
]

export const ALL_MENTORS = [
  {
    id: 'm1',
    name: 'Prof. K. Narayanan',
    email: 'narayanan.mentor@iitm.ac.in',
    phone: '+91 98765 43210',
    university: 'Indian Institute of Technology Madras (IIT Madras)',
    universityId: 'u2',
    designation: 'Associate Professor',
    department: 'Civil & Environmental Engineering',
    deptCode: 'CIV-ENV',
    experience: '12+ Years',
    domains: ['Water Sanitation & Supply', 'Urban Drainage & Flood Mitigation', 'Environmental Testing'],
    skills: ['Environmental Testing', 'Civil & Structural Engineering', 'GIS & Spatial Mapping', 'Water Quality Analytics'],
    avatar: 'KN',
    status: 'ACTIVE',
  },
  {
    id: 'm2',
    name: 'Dr. Priya Sundararajan',
    email: 'priya.sundar@annauniv.edu',
    phone: '+91 98452 11223',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    designation: 'Professor & HOD',
    department: 'Computer Science & Engineering (AI/Data)',
    deptCode: 'CSE-DS',
    experience: '15+ Years',
    domains: ['Renewable Energy & Solar Grids', 'AI for Social Impact', 'Smart Mobility'],
    skills: ['Full Stack Web Development', 'Machine Learning & Computer Vision', 'Data Science & Analytics', 'IoT Sensor Networks'],
    avatar: 'PS',
    status: 'ACTIVE',
  },
  {
    id: 'm3',
    name: 'Dr. Anandha Kumar',
    email: 'anandhakumar.agri@tnau.ac.in',
    phone: '+91 97891 55443',
    university: 'Tamil Nadu Agricultural University (TNAU), Coimbatore',
    universityId: 'u12',
    designation: 'Chief Scientist & Professor',
    department: 'Agronomy, Soil Science & Water Management',
    deptCode: 'AGR-SOIL',
    experience: '18+ Years',
    domains: ['Agricultural Tech & Irrigation', 'Soil Degradation', 'Water Management'],
    skills: ['Soil Salinity Probing', 'Crop Yield Analytics', 'LoRa Precision Irrigation', 'GIS Mapping'],
    avatar: 'AK',
    status: 'ACTIVE',
  },
  {
    id: 'm4',
    name: 'Prof. Meenakshi Raman',
    email: 'meenakshi.law@nlsiu.ac.in',
    phone: '+91 99012 33445',
    university: 'National Law School of India University (NLSIU), Bengaluru',
    universityId: 'u14',
    designation: 'Chair Professor of Public Law',
    department: 'Cyber Law, Data Governance & Public Policy',
    deptCode: 'LAW-CYB',
    experience: '14+ Years',
    domains: ['Public Policy & Privacy', 'Digital Rights', 'Data Governance'],
    skills: ['DPDP Act Compliance', 'Legislative Drafting', 'Ethical AI Governance', 'Civic Rights Law'],
    avatar: 'MR',
    status: 'ACTIVE',
  },
  {
    id: 'm5',
    name: 'Dr. V. Senthil Nathan',
    email: 'senthil.nathan@mmc.edu.in',
    phone: '+91 94441 77889',
    university: 'Madras Medical College (MMC), Chennai',
    universityId: 'u13',
    designation: 'Head of Community Medicine',
    department: 'Public Health & Community Epidemiology',
    deptCode: 'MED-PUB',
    experience: '20+ Years',
    domains: ['Rural Healthcare & Telemedicine', 'Epidemic Prevention', 'Vector Control'],
    skills: ['Spatial Epidemiology', 'Biostatistics', 'Community Field Trials', 'Preventive Healthcare Protocols'],
    avatar: 'SN',
    status: 'ACTIVE',
  },
  {
    id: 'm6',
    name: 'Dr. H. Nagarathna',
    email: 'nagarathna.yoga@svyasa.edu.in',
    phone: '+91 98860 99881',
    university: 'S-VYASA Yoga University, Bengaluru',
    universityId: 'u15',
    designation: 'Dean of Research & Clinical Yoga',
    department: 'Integrative Medicine & Yoga Sciences',
    deptCode: 'YOG-INT',
    experience: '22+ Years',
    domains: ['Yoga & Integrative Health', 'Occupational Ergonomics', 'Mental Health'],
    skills: ['Physiological Marker Assessment', 'HRV Analysis', 'Clinical Yoga Protocols', 'Ergonomic Surveys'],
    avatar: 'HN',
    status: 'ACTIVE',
  },
]

export const ALL_STUDENTS = [
  {
    id: 's1',
    name: 'Kavitha R.',
    email: 'kavitha.student@annauniv.edu',
    phone: '+91 98451 23456',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    department: 'Computer Science & Engineering (AI/Data)',
    deptCode: 'CSE-DS',
    yearOfStudy: '3rd Year (Junior)',
    skills: ['Data Science & Analytics', 'Full Stack Web Development', 'GIS & Spatial Mapping', 'Python'],
    domains: ['Water Sanitation & Supply', 'Smart Mobility', 'AI for Social Impact'],
    avatar: 'KR',
    status: 'ACTIVE',
  },
  {
    id: 's2',
    name: 'Vignesh M.',
    email: 'vignesh.civil@annauniv.edu',
    phone: '+91 99401 22334',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    department: 'Civil & Environmental Engineering',
    deptCode: 'CIV-ENV',
    yearOfStudy: '4th Year (Senior)',
    skills: ['Civil & Structural Engineering', 'CAD / 3D Modeling', 'Water Quality Analytics', 'Site Surveying'],
    domains: ['Water Sanitation & Supply', 'Urban Drainage & Flood Mitigation'],
    avatar: 'VM',
    status: 'ACTIVE',
  },
  {
    id: 's3',
    name: 'Ananya Sharma',
    email: 'ananya.env@iitm.ac.in',
    phone: '+91 98711 44556',
    university: 'Indian Institute of Technology Madras (IIT Madras)',
    universityId: 'u2',
    department: 'Civil & Environmental Engineering',
    deptCode: 'CIV-ENV',
    yearOfStudy: 'M.Tech (2nd Year)',
    skills: ['Environmental Testing', 'Spectrophotometry', 'Microbial Bioremediation', 'Project Management'],
    domains: ['Water Sanitation & Supply', 'Environmental Testing'],
    avatar: 'AS',
    status: 'ACTIVE',
  },
  {
    id: 's4',
    name: 'Rahul Krishna',
    email: 'rahul.ds@iitm.ac.in',
    phone: '+91 97902 33441',
    university: 'Indian Institute of Technology Madras (IIT Madras)',
    universityId: 'u2',
    department: 'Computer Science & Engineering (AI/Data)',
    deptCode: 'CSE-DS',
    yearOfStudy: '3rd Year (Junior)',
    skills: ['Machine Learning & Computer Vision', 'Time-series Forecasting', 'Embedded Systems / IoT', 'C++'],
    domains: ['Renewable Energy & Solar Grids', 'Smart Mobility'],
    avatar: 'RK',
    status: 'ACTIVE',
  },
  {
    id: 's5',
    name: 'Divya Bharathi',
    email: 'divya.agri@tnau.ac.in',
    phone: '+91 96291 88776',
    university: 'Tamil Nadu Agricultural University (TNAU), Coimbatore',
    universityId: 'u12',
    department: 'Agronomy, Soil Science & Water Management',
    deptCode: 'AGR-SOIL',
    yearOfStudy: '4th Year (Senior)',
    skills: ['Soil Salinity Probing', 'Crop Yield Analytics', 'Precision Irrigation', 'Field Scouting'],
    domains: ['Agricultural Tech & Irrigation', 'Soil Degradation'],
    avatar: 'DB',
    status: 'ACTIVE',
  },
  {
    id: 's6',
    name: 'Karthik S.',
    email: 'karthik.law@nlsiu.ac.in',
    phone: '+91 98801 66554',
    university: 'National Law School of India University (NLSIU), Bengaluru',
    universityId: 'u14',
    department: 'Cyber Law, Data Governance & Public Policy',
    deptCode: 'LAW-CYB',
    yearOfStudy: 'B.A. LL.B. (4th Year)',
    skills: ['DPDP Act Compliance', 'Legal Research', 'Policy Drafting', 'Data Governance Frameworks'],
    domains: ['Public Policy & Privacy', 'Digital Rights'],
    avatar: 'KS',
    status: 'ACTIVE',
  },
  {
    id: 's7',
    name: 'Sneha Patel',
    email: 'sneha.med@mmc.edu.in',
    phone: '+91 94451 99221',
    university: 'Madras Medical College (MMC), Chennai',
    universityId: 'u13',
    department: 'Public Health & Community Epidemiology',
    deptCode: 'MED-PUB',
    yearOfStudy: 'Final Year MBBS / Research Intern',
    skills: ['Public Health Surveying', 'Spatial Epidemiology', 'Clinical Data Analysis', 'Community Outreach'],
    domains: ['Rural Healthcare & Telemedicine', 'Epidemic Prevention'],
    avatar: 'SP',
    status: 'ACTIVE',
  },
  {
    id: 's8',
    name: 'Arvind Swaminathan',
    email: 'arvind.iot@annauniv.edu',
    phone: '+91 97103 44112',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    department: 'Electrical & Renewable Energy Systems',
    deptCode: 'EEE-RES',
    yearOfStudy: '3rd Year (Junior)',
    skills: ['Embedded Systems / IoT', 'Sensor Interfacing', 'LoRaWAN', 'PCB Design'],
    domains: ['Water Sanitation & Supply', 'Agricultural Tech & Irrigation', 'Renewable Energy & Solar Grids'],
    avatar: 'AS',
    status: 'ACTIVE',
  },
  {
    id: 's9',
    name: 'Meera Nair',
    email: 'meera.res@annauniv.edu',
    phone: '+91 98402 77884',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    department: 'Electrical & Renewable Energy Systems',
    deptCode: 'EEE-RES',
    yearOfStudy: '4th Year (Senior)',
    skills: ['Renewable Power Systems', 'Solar MPPT Algorithms', 'MATLAB/Simulink', 'CAD / 3D Modeling'],
    domains: ['Renewable Energy & Solar Grids'],
    avatar: 'MN',
    status: 'ACTIVE',
  },
  {
    id: 's10',
    name: 'Harish V.',
    email: 'harish.yoga@svyasa.edu.in',
    phone: '+91 99160 33221',
    university: 'S-VYASA Yoga University, Bengaluru',
    universityId: 'u15',
    department: 'Integrative Medicine & Yoga Sciences',
    deptCode: 'YOG-INT',
    yearOfStudy: 'M.Sc Yoga Therapy (2nd Year)',
    skills: ['Physiological Marker Assessment', 'HRV Biofeedback', 'Stress Protocol Design', 'Public Health Surveying'],
    domains: ['Yoga & Integrative Health', 'Occupational Ergonomics'],
    avatar: 'HV',
    status: 'ACTIVE',
  },
]

export const INITIAL_GOVERNMENT_PROBLEMS = [
  {
    id: 'SETU-GOV-RES-301',
    title: 'Heavy Metal & Dye Contamination in Noyyal River Industrial Stretch',
    category: 'Water & Environmental Engineering',
    researchRequired: 'Multi-stage Nano-filtration Membrane Design & Microbial Bioremediation Kinetics',
    description: 'Industrial effluents containing Chromium (VI) and synthetic textile azo-dyes exceeding CPCB permissible levels by 320%. Groundwater within 4km radius is unfit for irrigation. Need scalable nano-cellulose filtration and in-situ bacterial biodegradation pilot.',
    location: 'Tiruppur Industrial Corridor, Ward 12 & Noyyal River Basin',
    severity: 'Critical',
    urgency: 'Immediate Action Required',
    submittedBy: 'Tamil Nadu Pollution Control Board (TNPCB) & District Municipal Collectorate',
    dateReceived: 'Aug 28, 2026',
    estimatedBudget: '₹ 18.5 Lakhs (Sanctioned Grant)',
    matchingDomains: ['Water Sanitation & Supply', 'Environmental Testing', 'Urban Drainage & Flood Mitigation'],
    matchingDepartments: ['Civil & Environmental Engineering', 'Biotechnology', 'Computer Science & Engineering (AI/Data)'],
    matchingMentorIds: ['m1', 'm2'],
    matchingStudentIds: ['s1', 's2', 's3', 's4', 's8'],
    matchingReason: 'Domain match: Environmental effluent testing, water quality monitoring IoT telemetry, and civil filtration design required.',
    evidenceCount: 4,
    evidence: [
      { title: 'Water Lab Spectrometry Report', type: 'PDF Document', size: '2.4 MB', date: 'Aug 28, 2026' },
      { title: 'Tiruppur Outfall Sediment Sample #4', type: 'Image / JPG', size: '3.1 MB', date: 'Aug 29, 2026' },
      { title: 'GIS Groundwater Conductivity Map', type: 'GIS Layer', size: '8.2 MB', date: 'Aug 30, 2026' },
    ],
    // Team slot state: 1 Mentor + 5 Students (FULL)
    assignedMentorId: 'm1',
    assignedStudentIds: ['s1', 's2', 's3', 's4', 's8'],
    status: 'IN_PROGRESS', // 'OPEN' | 'IN_PROGRESS' | 'COMPLETED'
    workflowStage: 'Field Prototyping & Pilot Testing',
    progressPercentage: 65,
    contributionsCount: 3,
  },
  {
    id: 'SETU-GOV-RES-302',
    title: 'Edge-AI Microgrid Inverter Balancing for High-Density Rooftop Solar',
    category: 'Renewable Energy & Smart Grid',
    researchRequired: 'Decentralized Edge-AI Voltage Fluctuation Control & Supercapacitor Buffer Topology',
    description: 'Rapid residential rooftop solar deployment is triggering feeder voltage instability and 24.3% reverse power flow line losses during peak 11 AM – 2 PM hours. Requires autonomous edge IoT smart inverters capable of local peer-to-peer load harmonic balancing without cloud latency.',
    location: 'Coimbatore South Distribution Circle, TANGEDCO',
    severity: 'High',
    urgency: 'Within 30 Days',
    submittedBy: 'Tamil Nadu Generation and Distribution Corporation (TANGEDCO)',
    dateReceived: 'Sep 01, 2026',
    estimatedBudget: '₹ 14.0 Lakhs',
    matchingDomains: ['Renewable Energy & Solar Grids', 'AI for Social Impact', 'Smart Mobility'],
    matchingDepartments: ['Computer Science & Engineering (AI/Data)', 'Electrical & Renewable Energy Systems'],
    matchingMentorIds: ['m2'],
    matchingStudentIds: ['s1', 's4', 's8', 's9'],
    matchingReason: 'Requires embedded microgrid control firmware, machine learning load forecasting, and high-frequency power electronics simulation.',
    evidenceCount: 3,
    evidence: [
      { title: 'TANGEDCO Feeder Telemetry Log (30 Days)', type: 'CSV Dataset', size: '14.5 MB', date: 'Sep 01, 2026' },
      { title: 'Substation Transformer Thermal Scan', type: 'Image / PNG', size: '4.8 MB', date: 'Sep 02, 2026' },
    ],
    // Team slot state: 1 Mentor + 3 Students (Open for 2 students)
    assignedMentorId: 'm2',
    assignedStudentIds: ['s1', 's4', 's9'],
    status: 'IN_PROGRESS',
    workflowStage: 'Simulation & Architecture Design',
    progressPercentage: 40,
    contributionsCount: 2,
  },
  {
    id: 'SETU-GOV-RES-303',
    title: 'Low-Cost Capacitive Soil Salinity Probing & Solar LoRa Telemetry',
    category: 'Agricultural Tech & Precision Irrigation',
    researchRequired: 'Calibrated Multi-depth Soil EC Sensors & Self-Powered LoRa Mesh for Alkaline Soils',
    description: 'Over 4,200 smallholder groundnut and turmeric farmers in the dryland belt face 35% crop yield loss due to subsurface salinity intrusion. Commercial probes cost ₹ 45,000+ per unit. Need an open-hardware soil EC sensor under ₹ 1,500 with solar-assisted low-power telemetry.',
    location: 'Vellore & Tirupathur Dryland Agricultural Zones',
    severity: 'High',
    urgency: 'Active Planting Season',
    submittedBy: 'Department of Agriculture & Farmers Welfare, Govt of Tamil Nadu',
    dateReceived: 'Sep 03, 2026',
    estimatedBudget: '₹ 9.5 Lakhs',
    matchingDomains: ['Agricultural Tech & Irrigation', 'Embedded Systems / IoT', 'Soil Degradation'],
    matchingDepartments: ['Agronomy, Soil Science & Water Management', 'Electrical & Renewable Energy Systems', 'Computer Science & Engineering (AI/Data)'],
    matchingMentorIds: ['m3'],
    matchingStudentIds: ['s1', 's5', 's8'],
    matchingReason: 'Domain match: Agronomy soil chemistry coupled with low-cost IoT sensor network fabrication and cloud dashboard.',
    evidenceCount: 2,
    evidence: [
      { title: 'Dryland Soil Mineral Analysis Profile', type: 'PDF Document', size: '1.8 MB', date: 'Sep 03, 2026' },
      { title: 'Farmer Cluster Yield Loss Survey Report', type: 'Spreadsheet', size: '650 KB', date: 'Sep 03, 2026' },
    ],
    // Team slot state: 0 Mentors + 2 Students (Open for 1 mentor & 3 students)
    assignedMentorId: null,
    assignedStudentIds: ['s5', 's8'],
    status: 'OPEN',
    workflowStage: 'Team Formation & Problem Formulation',
    progressPercentage: 15,
    contributionsCount: 1,
  },
  {
    id: 'SETU-GOV-RES-304',
    title: 'Privacy-Preserving Civic Data Anonymization Schema under DPDP Act 2023',
    category: 'Law, Data Governance & Public Policy',
    researchRequired: 'Differential Privacy Protocol for Municipal GIS Complaint Databases & Redaction Guidelines',
    description: 'State civic portals aggregate citizen grievance locations and photos. A legally compliant differential privacy and cryptographic pseudonymization framework is needed to publish open civic research datasets without violating citizen privacy.',
    location: 'Greater Chennai Corporation & State e-Governance Agency',
    severity: 'Medium',
    urgency: 'Policy Review Deadline: Q4 2026',
    submittedBy: 'Tamil Nadu e-Governance Agency (TNeGA) & Dept of IT',
    dateReceived: 'Sep 02, 2026',
    estimatedBudget: '₹ 7.0 Lakhs',
    matchingDomains: ['Public Policy & Privacy', 'Digital Rights', 'Data Science & Analytics'],
    matchingDepartments: ['Cyber Law, Data Governance & Public Policy', 'Computer Science & Engineering (AI/Data)'],
    matchingMentorIds: ['m4'],
    matchingStudentIds: ['s1', 's6'],
    matchingReason: 'Legal policy analysis of DPDP Act clauses blended with differential privacy algorithmic proofs.',
    evidenceCount: 2,
    evidence: [
      { title: 'TNeGA Civic Grievance Schema Spec v2.1', type: 'PDF Document', size: '1.2 MB', date: 'Sep 02, 2026' },
    ],
    // Team slot state: 1 Mentor + 1 Student (Open for 4 students)
    assignedMentorId: 'm4',
    assignedStudentIds: ['s6'],
    status: 'IN_PROGRESS',
    workflowStage: 'Policy Draft & Algorithm Verification',
    progressPercentage: 30,
    contributionsCount: 1,
  },
  {
    id: 'SETU-GOV-RES-305',
    title: 'Micro-Spatial GIS Clustering & Drone Thermal Larval Detection for Dengue',
    category: 'Medical & Healthcare Sciences',
    researchRequired: 'Thermal IR Image Classification of Rooftop Water Stagnation & Spatio-Temporal R0 Modeling',
    description: 'Recurrent seasonal dengue outbreaks in dense urban wards require automated aerial drone infrared detection of stagnant overhead tanks combined with meteorological predictive infection modeling.',
    location: 'Madurai City Municipal Corporation, Wards 18–34',
    severity: 'Critical',
    urgency: 'Pre-Monsoon Preparedness',
    submittedBy: 'Directorate of Public Health & Preventive Medicine, Tamil Nadu',
    dateReceived: 'Aug 30, 2026',
    estimatedBudget: '₹ 16.0 Lakhs',
    matchingDomains: ['Rural Healthcare & Telemedicine', 'GIS & Spatial Mapping', 'AI for Social Impact'],
    matchingDepartments: ['Public Health & Community Epidemiology', 'Computer Science & Engineering (AI/Data)'],
    matchingMentorIds: ['m5', 'm2'],
    matchingStudentIds: ['s1', 's4', 's7'],
    matchingReason: 'Epidemiological field methodology paired with drone computer vision and spatial regression modeling.',
    evidenceCount: 3,
    evidence: [
      { title: 'Madurai 5-Year Dengue Serotype Survey', type: 'PDF Document', size: '5.6 MB', date: 'Aug 30, 2026' },
      { title: 'Drone Thermal Overhead Imagery Samples', type: 'ZIP Archive', size: '28.4 MB', date: 'Aug 31, 2026' },
    ],
    // Team slot state: 1 Mentor + 3 Students (Open for 2 students)
    assignedMentorId: 'm5',
    assignedStudentIds: ['s1', 's4', 's7'],
    status: 'IN_PROGRESS',
    workflowStage: 'Algorithm Training & Field Validation',
    progressPercentage: 55,
    contributionsCount: 2,
  },
  {
    id: 'SETU-GOV-RES-306',
    title: 'Standardized Yoga & Ergonomic Stress Remediation Protocol for Sanitation Workers',
    category: 'Yoga & Traditional Medicine',
    researchRequired: 'Physiological Biomarker Tracking (Salivary Cortisol, HRV) & Musculoskeletal Rehab Protocol',
    description: 'Over 800 manual municipal sanitation workers suffer chronic lower back trauma and psychological burnout. Objective is to formulate and clinically validate an evidence-based 15-minute pre-shift yogic breathing and dynamic stretching regimen.',
    location: 'Tiruchirappalli City Corporation Sanitation Depots',
    severity: 'Medium',
    urgency: 'Employee Welfare Quarter 3',
    submittedBy: 'Tiruchirappalli City Corporation & Labour Welfare Board',
    dateReceived: 'Sep 04, 2026',
    estimatedBudget: '₹ 5.5 Lakhs',
    matchingDomains: ['Yoga & Integrative Health', 'Public Health Surveying', 'Occupational Ergonomics'],
    matchingDepartments: ['Integrative Medicine & Yoga Sciences', 'Public Health & Community Epidemiology'],
    matchingMentorIds: ['m6'],
    matchingStudentIds: ['s7', 's10'],
    matchingReason: 'Clinical research in physiological stress markers combined with standardized yogic therapy intervention.',
    evidenceCount: 1,
    evidence: [
      { title: 'Municipal Worker Health Screening Baseline', type: 'PDF Document', size: '3.3 MB', date: 'Sep 04, 2026' },
    ],
    // Team slot state: 0 Mentors + 0 Students (Completely open: 1 mentor, 5 students)
    assignedMentorId: null,
    assignedStudentIds: [],
    status: 'OPEN',
    workflowStage: 'Awaiting Faculty & Student Adoption',
    progressPercentage: 0,
    contributionsCount: 0,
  },
]

export const INITIAL_APPROVAL_REQUESTS = [
  {
    id: 'req-m-101',
    name: 'Dr. S. K. Balamurugan',
    email: 'bala.civil@annauniv.edu',
    role: 'mentor',
    roleLabel: 'Faculty Mentor',
    department: 'Civil & Environmental Engineering',
    deptCode: 'CIV-ENV',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    designation: 'Associate Professor',
    experience: '11 Years',
    domains: ['Urban Drainage & Flood Mitigation', 'Water Sanitation & Supply'],
    skills: ['Hydrological Modeling', 'SWMM Simulation', 'Flood Risk Analytics'],
    registrationDate: 'Sep 04, 2026 • 10:15 AM',
    status: 'PENDING', // 'PENDING' | 'APPROVED' | 'REJECTED'
    idCardDoc: 'Faculty_ID_Balau.pdf',
    notes: 'Submitted institutional credentials and AICTE faculty ID.',
  },
  {
    id: 'req-m-102',
    name: 'Dr. G. Lakshmi Prasanna',
    email: 'lakshmi.eee@annauniv.edu',
    role: 'mentor',
    roleLabel: 'Faculty Mentor',
    department: 'Electrical & Renewable Energy Systems',
    deptCode: 'EEE-RES',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    designation: 'Assistant Professor (Sr. Grade)',
    experience: '8 Years',
    domains: ['Renewable Energy & Solar Grids', 'Smart Mobility'],
    skills: ['Battery Management Systems', 'Electric Vehicle Charging Inverters', 'MATLAB'],
    registrationDate: 'Sep 04, 2026 • 02:40 PM',
    status: 'PENDING',
    idCardDoc: 'Faculty_ID_Lakshmi.pdf',
    notes: 'Awaiting Department Chair sign-off.',
  },
  {
    id: 'req-s-201',
    name: 'Gowtham Chandran',
    email: 'gowtham.c@student.annauniv.edu',
    role: 'student',
    roleLabel: 'Student Innovator',
    department: 'Computer Science & Engineering (AI/Data)',
    deptCode: 'CSE-DS',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    yearOfStudy: '3rd Year (Junior)',
    domains: ['AI for Social Impact', 'Smart Mobility'],
    skills: ['Machine Learning', 'FastAPI', 'React', 'Computer Vision'],
    registrationDate: 'Sep 05, 2026 • 09:10 AM',
    status: 'PENDING',
    idCardDoc: 'Student_ID_Gowtham_2024.pdf',
    notes: 'Verified university roll number: 2023CS1084.',
  },
  {
    id: 'req-s-202',
    name: 'Pooja Venkatesh',
    email: 'pooja.env@student.annauniv.edu',
    role: 'student',
    roleLabel: 'Student Innovator',
    department: 'Civil & Environmental Engineering',
    deptCode: 'CIV-ENV',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    yearOfStudy: '4th Year (Senior)',
    domains: ['Water Sanitation & Supply', 'Waste Management & Recycling'],
    skills: ['Water Quality Testing', 'AutoCAD', 'Environmental Impact Assessment'],
    registrationDate: 'Sep 05, 2026 • 11:30 AM',
    status: 'PENDING',
    idCardDoc: 'Student_ID_Pooja_2023.pdf',
    notes: 'Interested in Noyyal Basin bioremediation project.',
  },
  {
    id: 'req-s-203',
    name: 'Mohammed Aslam',
    email: 'aslam.eee@student.annauniv.edu',
    role: 'student',
    roleLabel: 'Student Innovator',
    department: 'Electrical & Renewable Energy Systems',
    deptCode: 'EEE-RES',
    university: 'Anna University, Chennai',
    universityId: 'u1',
    yearOfStudy: '2nd Year (Sophomore)',
    domains: ['Renewable Energy & Solar Grids'],
    skills: ['Arduino', 'PCB Soldering', 'C Programming'],
    registrationDate: 'Sep 03, 2026 • 04:20 PM',
    status: 'APPROVED',
    idCardDoc: 'Student_ID_Aslam.pdf',
    notes: 'Approved by University Administrator on Sep 3.',
  },
]

export const INITIAL_CONTRIBUTIONS = [
  {
    id: 'cnt-901',
    problemId: 'SETU-GOV-RES-301',
    problemTitle: 'Heavy Metal & Dye Contamination in Noyyal River Industrial Stretch',
    authorId: 'm1',
    authorName: 'Prof. K. Narayanan',
    authorRole: 'Mentor',
    authorUniversity: 'IIT Madras',
    title: 'Stage-1 Technical Feasibility: Bacterial Consortium Bioremediation Kinetics',
    type: 'Research Proposal & Lab Report',
    submissionDate: 'Sep 01, 2026 • 11:20 AM',
    summary: 'Isolated Bacillus sp. and Pseudomonas strains capable of reducing 84% Chromium (VI) to Cr(III) within 48-hour bioreactor test cycle. Lab protocol ready for scaling.',
    attachments: [
      { name: 'Noyyal_Bioremediation_Lab_Report_v1.pdf', size: '3.4 MB' },
      { name: 'Chromium_Reduction_Kinetics_Chart.xlsx', size: '820 KB' },
    ],
    status: 'UNDER_ADMIN_REVIEW',
    rating: 'A+ Verified',
  },
  {
    id: 'cnt-902',
    problemId: 'SETU-GOV-RES-301',
    problemTitle: 'Heavy Metal & Dye Contamination in Noyyal River Industrial Stretch',
    authorId: 's1',
    authorName: 'Kavitha R. & Team',
    authorRole: 'Student Team',
    authorUniversity: 'Anna University',
    title: 'IoT Multi-Sensor Turbidity & Total Dissolved Solids Telemetry Node',
    type: 'Prototype Output',
    submissionDate: 'Sep 03, 2026 • 03:45 PM',
    summary: 'Built solar-powered ESP32 floating telemetry buoy with optical turbidity probe, pH sensor, and GPS. Live data transmission over GSM MQTT to SETU dashboard.',
    attachments: [
      { name: 'Hardware_Schematic_Gerber_v2.zip', size: '6.1 MB' },
      { name: 'Field_Deployment_Photo_Tiruppur.jpg', size: '2.8 MB' },
    ],
    status: 'APPROVED_BY_MENTOR',
    rating: 'High Innovation',
  },
  {
    id: 'cnt-903',
    problemId: 'SETU-GOV-RES-302',
    problemTitle: 'Edge-AI Microgrid Inverter Balancing for High-Density Rooftop Solar',
    authorId: 'm2',
    authorName: 'Dr. Priya Sundararajan',
    authorRole: 'Mentor',
    authorUniversity: 'Anna University',
    title: 'Reinforcement Learning Voltage Regulation for 11kV Radial Feeders',
    type: 'Research Proposal',
    submissionDate: 'Sep 04, 2026 • 09:30 AM',
    summary: 'Developed Deep Q-Network (DQN) agent for coordinated active/reactive power injection (Volt-VAR) with 98.4% grid compliance in MATLAB IEEE 33-bus simulation.',
    attachments: [
      { name: 'IEEE33_VoltVAR_Simulation_Results.pdf', size: '4.2 MB' },
    ],
    status: 'SANCTIONED_PILOT',
    rating: 'Recommended for CPCB Grant',
  },
]

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'New Government Research Problem Dispatched',
    message: 'Tamil Nadu Pollution Control Board has dispatched a Critical Research Problem: "Heavy Metal & Dye Contamination in Noyyal River".',
    timestamp: '2 hours ago',
    type: 'government_alert',
    isRead: false,
    problemId: 'SETU-GOV-RES-301',
  },
  {
    id: 'notif-2',
    title: 'Student Team Slot Reached 5/5 Capacity',
    message: 'Problem SETU-GOV-RES-301 student slots are now fully occupied (5/5). Team assembly complete.',
    timestamp: '5 hours ago',
    type: 'team_update',
    isRead: false,
    problemId: 'SETU-GOV-RES-301',
  },
  {
    id: 'notif-3',
    title: 'Pending Faculty Registration',
    message: 'Dr. S. K. Balamurugan submitted a new Faculty Mentor registration awaiting Administrator verification.',
    timestamp: '1 day ago',
    type: 'approval_req',
    isRead: true,
  },
  {
    id: 'notif-4',
    title: 'New Research Contribution Uploaded',
    message: 'Prof. K. Narayanan uploaded a technical lab report for problem SETU-GOV-RES-301.',
    timestamp: '2 days ago',
    type: 'contribution',
    isRead: true,
    problemId: 'SETU-GOV-RES-301',
  },
]

export const TIME_BASED_STATISTICS = {
  '7d': {
    label: 'Last 7 Days',
    totalProblemsReceived: 6,
    newProblems: 4,
    matchingOpportunities: 5,
    problemsAccepted: 3,
    activeMentees: 9,
    contributionsSubmitted: 3,
    weeklyActivity: [
      { day: 'Mon', count: 2, problems: 1 },
      { day: 'Tue', count: 4, problems: 2 },
      { day: 'Wed', count: 3, problems: 1 },
      { day: 'Thu', count: 6, problems: 3 },
      { day: 'Fri', count: 5, problems: 2 },
      { day: 'Sat', count: 2, problems: 0 },
      { day: 'Sun', count: 1, problems: 0 },
    ],
  },
  '1m': {
    label: 'Last 1 Month',
    totalProblemsReceived: 18,
    newProblems: 12,
    matchingOpportunities: 14,
    problemsAccepted: 8,
    activeMentees: 24,
    contributionsSubmitted: 9,
    weeklyActivity: [
      { day: 'Week 1', count: 8, problems: 3 },
      { day: 'Week 2', count: 14, problems: 5 },
      { day: 'Week 3', count: 12, problems: 4 },
      { day: 'Week 4', count: 19, problems: 6 },
    ],
  },
  '3m': {
    label: 'Last 3 Months',
    totalProblemsReceived: 42,
    newProblems: 28,
    matchingOpportunities: 35,
    problemsAccepted: 21,
    activeMentees: 62,
    contributionsSubmitted: 27,
    weeklyActivity: [
      { day: 'Month 1', count: 32, problems: 11 },
      { day: 'Month 2', count: 45, problems: 14 },
      { day: 'Month 3', count: 58, problems: 17 },
    ],
  },
  '6m': {
    label: 'Last 6 Months',
    totalProblemsReceived: 88,
    newProblems: 64,
    matchingOpportunities: 72,
    problemsAccepted: 48,
    activeMentees: 135,
    contributionsSubmitted: 61,
    weeklyActivity: [
      { day: 'Month 1', count: 25, problems: 8 },
      { day: 'Month 2', count: 34, problems: 12 },
      { day: 'Month 3', count: 42, problems: 15 },
      { day: 'Month 4', count: 50, problems: 16 },
      { day: 'Month 5', count: 58, problems: 18 },
      { day: 'Month 6', count: 68, problems: 19 },
    ],
  },
  '1y': {
    label: 'Last 1 Year',
    totalProblemsReceived: 164,
    newProblems: 128,
    matchingOpportunities: 142,
    problemsAccepted: 94,
    activeMentees: 280,
    contributionsSubmitted: 118,
    weeklyActivity: [
      { day: 'Q1', count: 68, problems: 24 },
      { day: 'Q2', count: 95, problems: 32 },
      { day: 'Q3', count: 124, problems: 48 },
      { day: 'Q4', count: 164, problems: 60 },
    ],
  },
}
