"""complete setu schema

Revision ID: feb00d16101f
Revises: 0c4d6c5d5bfc
Create Date: 2026-09-05 20:37:20.756134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb00d16101f'
down_revision: Union[str, Sequence[str], None] = '0c4d6c5d5bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('registration_details', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('headquarters', sa.String(length=150), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporates_id'), 'corporates', ['id'], unique=False)
    op.create_index(op.f('ix_corporates_industry'), 'corporates', ['industry'], unique=False)
    op.create_table('government_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_organizations_district'), 'government_organizations', ['district'], unique=False)
    op.create_index(op.f('ix_government_organizations_id'), 'government_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_government_organizations_level'), 'government_organizations', ['level'], unique=False)
    op.create_index(op.f('ix_government_organizations_state'), 'government_organizations', ['state'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('contact_details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_city'), 'universities', ['city'], unique=False)
    op.create_index(op.f('ix_universities_code'), 'universities', ['code'], unique=True)
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_state'), 'universities', ['state'], unique=False)
    op.create_table('csr_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('geographic_preferences', sa.JSON(), nullable=True),
    sa.Column('funding_range', sa.JSON(), nullable=True),
    sa.Column('preferred_problem_types', sa.JSON(), nullable=True),
    sa.Column('preferred_project_stages', sa.JSON(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_profiles_corporate_id'), 'csr_profiles', ['corporate_id'], unique=True)
    op.create_index(op.f('ix_csr_profiles_id'), 'csr_profiles', ['id'], unique=False)
    op.create_table('csr_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_users_corporate_id'), 'csr_users', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_csr_users_id'), 'csr_users', ['id'], unique=False)
    op.create_index(op.f('ix_csr_users_user_id'), 'csr_users', ['user_id'], unique=True)
    op.create_table('government_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('government_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['government_id'], ['government_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_departments_government_id'), 'government_departments', ['government_id'], unique=False)
    op.create_index(op.f('ix_government_departments_id'), 'government_departments', ['id'], unique=False)
    op.create_index(op.f('ix_government_departments_jurisdiction'), 'government_departments', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_government_departments_name'), 'government_departments', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('university_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_departments_id'), 'university_departments', ['id'], unique=False)
    op.create_index(op.f('ix_university_departments_university_id'), 'university_departments', ['university_id'], unique=False)
    op.create_table('university_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_teams_id'), 'university_teams', ['id'], unique=False)
    op.create_index(op.f('ix_university_teams_university_id'), 'university_teams', ['university_id'], unique=False)
    op.create_table('government_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('government_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['government_departments.id'], ),
    sa.ForeignKeyConstraint(['government_id'], ['government_organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_users_department_id'), 'government_users', ['department_id'], unique=False)
    op.create_index(op.f('ix_government_users_government_id'), 'government_users', ['government_id'], unique=False)
    op.create_index(op.f('ix_government_users_id'), 'government_users', ['id'], unique=False)
    op.create_index(op.f('ix_government_users_user_id'), 'government_users', ['user_id'], unique=True)
    op.create_table('university_mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('expertise', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('profile_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['university_departments.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_mentors_department_id'), 'university_mentors', ['department_id'], unique=False)
    op.create_index(op.f('ix_university_mentors_id'), 'university_mentors', ['id'], unique=False)
    op.create_index(op.f('ix_university_mentors_university_id'), 'university_mentors', ['university_id'], unique=False)
    op.create_index(op.f('ix_university_mentors_user_id'), 'university_mentors', ['user_id'], unique=True)
    op.create_table('university_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('profile_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['university_departments.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_students_department_id'), 'university_students', ['department_id'], unique=False)
    op.create_index(op.f('ix_university_students_id'), 'university_students', ['id'], unique=False)
    op.create_index(op.f('ix_university_students_university_id'), 'university_students', ['university_id'], unique=False)
    op.create_index(op.f('ix_university_students_user_id'), 'university_students', ['user_id'], unique=True)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('title_generated', sa.String(length=255), nullable=True),
    sa.Column('category_predicted', sa.String(length=100), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('severity_factors', sa.JSON(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('duplicate_detected', sa.Boolean(), nullable=False),
    sa.Column('duplicate_report_ids', sa.JSON(), nullable=True),
    sa.Column('research_classification', sa.String(length=50), nullable=False),
    sa.Column('research_confidence', sa.Float(), nullable=False),
    sa.Column('location_interpretation', sa.String(length=255), nullable=True),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_report_id'), 'ai_analyses', ['report_id'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_citizen_id'), 'appeals', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_index(op.f('ix_appeals_report_id'), 'appeals', ['report_id'], unique=False)
    op.create_table('problem_csr_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('corporate_id', sa.Integer(), nullable=False),
    sa.Column('csr_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matching_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.id'], ),
    sa.ForeignKeyConstraint(['csr_id'], ['csr_profiles.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_csr_matches_corporate_id'), 'problem_csr_matches', ['corporate_id'], unique=False)
    op.create_index(op.f('ix_problem_csr_matches_csr_id'), 'problem_csr_matches', ['csr_id'], unique=False)
    op.create_index(op.f('ix_problem_csr_matches_id'), 'problem_csr_matches', ['id'], unique=False)
    op.create_index(op.f('ix_problem_csr_matches_report_id'), 'problem_csr_matches', ['report_id'], unique=False)
    op.create_table('problem_university_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matching_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['university_departments.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['university_mentors.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_university_matches_department_id'), 'problem_university_matches', ['department_id'], unique=False)
    op.create_index(op.f('ix_problem_university_matches_id'), 'problem_university_matches', ['id'], unique=False)
    op.create_index(op.f('ix_problem_university_matches_mentor_id'), 'problem_university_matches', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_problem_university_matches_report_id'), 'problem_university_matches', ['report_id'], unique=False)
    op.create_index(op.f('ix_problem_university_matches_university_id'), 'problem_university_matches', ['university_id'], unique=False)
    op.create_table('report_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_histories_id'), 'report_histories', ['id'], unique=False)
    op.create_index(op.f('ix_report_histories_report_id'), 'report_histories', ['report_id'], unique=False)
    op.create_table('report_status_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_status_histories_id'), 'report_status_histories', ['id'], unique=False)
    op.create_index(op.f('ix_report_status_histories_report_id'), 'report_status_histories', ['report_id'], unique=False)
    op.create_table('report_supports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'citizen_id', name='uq_report_citizen_support')
    )
    op.create_index(op.f('ix_report_supports_citizen_id'), 'report_supports', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_report_supports_id'), 'report_supports', ['id'], unique=False)
    op.create_index(op.f('ix_report_supports_report_id'), 'report_supports', ['report_id'], unique=False)
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('solution_details', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolutions_id'), 'resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_resolutions_report_id'), 'resolutions', ['report_id'], unique=False)
    op.create_table('solution_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_projects_id'), 'solution_projects', ['id'], unique=False)
    op.create_index(op.f('ix_solution_projects_report_id'), 'solution_projects', ['report_id'], unique=False)
    op.create_index(op.f('ix_solution_projects_stage'), 'solution_projects', ['stage'], unique=False)
    op.create_index(op.f('ix_solution_projects_status'), 'solution_projects', ['status'], unique=False)
    op.create_table('university_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['university_students.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['university_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_team_members_id'), 'university_team_members', ['id'], unique=False)
    op.create_index(op.f('ix_university_team_members_student_id'), 'university_team_members', ['student_id'], unique=False)
    op.create_index(op.f('ix_university_team_members_team_id'), 'university_team_members', ['team_id'], unique=False)
    op.create_table('university_team_mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['university_mentors.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['university_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_team_mentors_id'), 'university_team_mentors', ['id'], unique=False)
    op.create_index(op.f('ix_university_team_mentors_mentor_id'), 'university_team_mentors', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_university_team_mentors_team_id'), 'university_team_mentors', ['team_id'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['solution_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_milestones_id'), 'project_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_project_milestones_project_id'), 'project_milestones', ['project_id'], unique=False)
    op.create_table('project_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('participant_type', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['solution_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_participants_id'), 'project_participants', ['id'], unique=False)
    op.create_index(op.f('ix_project_participants_project_id'), 'project_participants', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_participants_user_id'), 'project_participants', ['user_id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_project_participants_user_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_project_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_id'), table_name='project_participants')
    op.drop_table('project_participants')
    op.drop_index(op.f('ix_project_milestones_project_id'), table_name='project_milestones')
    op.drop_index(op.f('ix_project_milestones_id'), table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index(op.f('ix_university_team_mentors_team_id'), table_name='university_team_mentors')
    op.drop_index(op.f('ix_university_team_mentors_mentor_id'), table_name='university_team_mentors')
    op.drop_index(op.f('ix_university_team_mentors_id'), table_name='university_team_mentors')
    op.drop_table('university_team_mentors')
    op.drop_index(op.f('ix_university_team_members_team_id'), table_name='university_team_members')
    op.drop_index(op.f('ix_university_team_members_student_id'), table_name='university_team_members')
    op.drop_index(op.f('ix_university_team_members_id'), table_name='university_team_members')
    op.drop_table('university_team_members')
    op.drop_index(op.f('ix_solution_projects_status'), table_name='solution_projects')
    op.drop_index(op.f('ix_solution_projects_stage'), table_name='solution_projects')
    op.drop_index(op.f('ix_solution_projects_report_id'), table_name='solution_projects')
    op.drop_index(op.f('ix_solution_projects_id'), table_name='solution_projects')
    op.drop_table('solution_projects')
    op.drop_index(op.f('ix_resolutions_report_id'), table_name='resolutions')
    op.drop_index(op.f('ix_resolutions_id'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_report_supports_report_id'), table_name='report_supports')
    op.drop_index(op.f('ix_report_supports_id'), table_name='report_supports')
    op.drop_index(op.f('ix_report_supports_citizen_id'), table_name='report_supports')
    op.drop_table('report_supports')
    op.drop_index(op.f('ix_report_status_histories_report_id'), table_name='report_status_histories')
    op.drop_index(op.f('ix_report_status_histories_id'), table_name='report_status_histories')
    op.drop_table('report_status_histories')
    op.drop_index(op.f('ix_report_histories_report_id'), table_name='report_histories')
    op.drop_index(op.f('ix_report_histories_id'), table_name='report_histories')
    op.drop_table('report_histories')
    op.drop_index(op.f('ix_problem_university_matches_university_id'), table_name='problem_university_matches')
    op.drop_index(op.f('ix_problem_university_matches_report_id'), table_name='problem_university_matches')
    op.drop_index(op.f('ix_problem_university_matches_mentor_id'), table_name='problem_university_matches')
    op.drop_index(op.f('ix_problem_university_matches_id'), table_name='problem_university_matches')
    op.drop_index(op.f('ix_problem_university_matches_department_id'), table_name='problem_university_matches')
    op.drop_table('problem_university_matches')
    op.drop_index(op.f('ix_problem_csr_matches_report_id'), table_name='problem_csr_matches')
    op.drop_index(op.f('ix_problem_csr_matches_id'), table_name='problem_csr_matches')
    op.drop_index(op.f('ix_problem_csr_matches_csr_id'), table_name='problem_csr_matches')
    op.drop_index(op.f('ix_problem_csr_matches_corporate_id'), table_name='problem_csr_matches')
    op.drop_table('problem_csr_matches')
    op.drop_index(op.f('ix_appeals_report_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_citizen_id'), table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_ai_analyses_report_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_university_students_user_id'), table_name='university_students')
    op.drop_index(op.f('ix_university_students_university_id'), table_name='university_students')
    op.drop_index(op.f('ix_university_students_id'), table_name='university_students')
    op.drop_index(op.f('ix_university_students_department_id'), table_name='university_students')
    op.drop_table('university_students')
    op.drop_index(op.f('ix_university_mentors_user_id'), table_name='university_mentors')
    op.drop_index(op.f('ix_university_mentors_university_id'), table_name='university_mentors')
    op.drop_index(op.f('ix_university_mentors_id'), table_name='university_mentors')
    op.drop_index(op.f('ix_university_mentors_department_id'), table_name='university_mentors')
    op.drop_table('university_mentors')
    op.drop_index(op.f('ix_government_users_user_id'), table_name='government_users')
    op.drop_index(op.f('ix_government_users_id'), table_name='government_users')
    op.drop_index(op.f('ix_government_users_government_id'), table_name='government_users')
    op.drop_index(op.f('ix_government_users_department_id'), table_name='government_users')
    op.drop_table('government_users')
    op.drop_index(op.f('ix_university_teams_university_id'), table_name='university_teams')
    op.drop_index(op.f('ix_university_teams_id'), table_name='university_teams')
    op.drop_table('university_teams')
    op.drop_index(op.f('ix_university_departments_university_id'), table_name='university_departments')
    op.drop_index(op.f('ix_university_departments_id'), table_name='university_departments')
    op.drop_table('university_departments')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_government_departments_name'), table_name='government_departments')
    op.drop_index(op.f('ix_government_departments_jurisdiction'), table_name='government_departments')
    op.drop_index(op.f('ix_government_departments_id'), table_name='government_departments')
    op.drop_index(op.f('ix_government_departments_government_id'), table_name='government_departments')
    op.drop_table('government_departments')
    op.drop_index(op.f('ix_csr_users_user_id'), table_name='csr_users')
    op.drop_index(op.f('ix_csr_users_id'), table_name='csr_users')
    op.drop_index(op.f('ix_csr_users_corporate_id'), table_name='csr_users')
    op.drop_table('csr_users')
    op.drop_index(op.f('ix_csr_profiles_id'), table_name='csr_profiles')
    op.drop_index(op.f('ix_csr_profiles_corporate_id'), table_name='csr_profiles')
    op.drop_table('csr_profiles')
    op.drop_index(op.f('ix_universities_state'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_code'), table_name='universities')
    op.drop_index(op.f('ix_universities_city'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_government_organizations_state'), table_name='government_organizations')
    op.drop_index(op.f('ix_government_organizations_level'), table_name='government_organizations')
    op.drop_index(op.f('ix_government_organizations_id'), table_name='government_organizations')
    op.drop_index(op.f('ix_government_organizations_district'), table_name='government_organizations')
    op.drop_table('government_organizations')
    op.drop_index(op.f('ix_corporates_industry'), table_name='corporates')
    op.drop_index(op.f('ix_corporates_id'), table_name='corporates')
    op.drop_table('corporates')
    # ### end Alembic commands ###
