// 45 Civic Categories
export const CIVIC_CATEGORIES = [
  'All Categories',
  'Water Supply',
  'Drinking Water',
  'Electricity',
  'Street Lighting',
  'Roads',
  'Traffic',
  'Public Transport',
  'Drainage',
  'Sewage',
  'Waste Management',
  'Sanitation',
  'Public Toilets',
  'Healthcare',
  'Government Hospitals',
  'Education',
  'Government Schools',
  'Public Safety',
  'Road Safety',
  'Flood Management',
  'Stormwater',
  'Lakes & Water Bodies',
  'Environmental Pollution',
  'Air Quality',
  'Noise Pollution',
  'Public Parks',
  'Public Spaces',
  'Footpaths',
  'Accessibility',
  'Rural Infrastructure',
  'Urban Infrastructure',
  'Housing',
  'Agriculture',
  'Irrigation',
  'Public Facilities',
  'Community Infrastructure',
  'Disaster Management',
  'Emergency Services',
  'Animal Management',
  'Food & Public Distribution',
  'Digital Connectivity',
  'Public Information',
  'Wastewater',
  'Coastal Infrastructure',
  'Climate Resilience',
  'Other Civic Issues',
]

// Demo CSR Company Profile Data
export const INITIAL_COMPANY_PROFILE = {
  companyName: 'ArunTech Industries Pvt. Ltd.',
  tagline: 'Empowering Communities Through Technology & Sustainable Infrastructure',
  logo: '🏢',
  registrationNo: 'CSR-TN-2021-88492',
  location: 'Tiruppur, Tamil Nadu',
  verified: true,
  csrCategories: [
    'Drinking Water',
    'Water Supply',
    'Government Schools',
    'Education',
    'Stormwater',
    'Lakes & Water Bodies',
    'Healthcare',
    'Government Hospitals',
    'Rural Infrastructure',
    'Sanitation',
    'Street Lighting',
    'Road Safety',
  ],
  csrFocusAreas: ['Drinking Water', 'Government Schools', 'Stormwater', 'Healthcare', 'Rural Infrastructure'],
  stats: {
    totalContributions: 875000,
    supportedProblems: 16,
    activeContributions: 4,
    completedContributions: 12,
    livesImpacted: 145000,
    districtsCovered: 8,
  },
}

// Helper to generate dynamic deadlines relative to current time
const now = Date.now()
const minutes = (m) => m * 60 * 1000
const hours = (h) => h * 3600 * 1000
const days = (d) => d * 24 * 3600 * 1000

// 22 Realistic Mock Problems
export const INITIAL_MOCK_PROBLEMS = [
  {
    id: 'SETU-PRB-1001',
    title: 'Drinking Water Shortage & Heavy Metal Contamination in Feeder Wells',
    category: 'Drinking Water',
    location: 'Kangeyam Block, Tiruppur District, Tamil Nadu',
    pincode: '638701',
    description:
      'The panchayat currently relies on groundwater borewells with elevated fluoride and total dissolved solids (TDS > 1800 ppm). During summer months, 3,200 rural households lack access to safe drinking water, forcing women and children to walk up to 4 km daily.',
    votes: 8420,
    severity: 'Critical', // Critical, High, Medium, Low
    researchStatus: 'Completed', // Completed | Not Required
    totalFundingRequired: 100000,
    currentFunding: 65000,
    deadline: new Date(now + days(5) + hours(14)).toISOString(),
    status: 'Active', // Active | Almost Funded | Fully Funded | Funding Closed | Completed
    universitySolution: {
      university: 'Kongu Engineering College',
      department: 'Department of Chemical & Environmental Engineering',
      studentTeam: 'AquaSense Innovation Group',
      mentor: 'Dr. R. Arun Kumar (HOD Environmental Engineering)',
      students: ['Nirmal Kumar', 'Aravind S', 'Harish M', 'Pranav K'],
      solutionSummary:
        'The team designed a low-power IoT-monitored solar membrane filtration skid equipped with inline TDS/pH sensors and automated backwash capabilities to reduce fluoride levels to under 1.0 ppm at ₹0.04/litre.',
      documentName: 'AquaSense_Water_Filtration_Feasibility_Report.pdf',
      documentSize: '3.4 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1002',
    title: 'Damaged Science & Computer Laboratory in Government Higher Secondary School',
    category: 'Government Schools',
    location: 'Sulur Town, Coimbatore District, Tamil Nadu',
    pincode: '641402',
    description:
      'The government school serving 680 rural students has broken laboratory benches, hazardous electrical wiring, and lacks functional physics/chemistry lab apparatus and desktop computers required for 10th & 12th board practicals.',
    votes: 4218,
    severity: 'High',
    researchStatus: 'Completed',
    totalFundingRequired: 75000,
    currentFunding: 25000,
    deadline: new Date(now + days(8) + hours(6)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'PSG College of Technology',
      department: 'Department of Electrical & Mechanical Engineering',
      studentTeam: 'EduLab Rebuild Team',
      mentor: 'Prof. S. Meenakshi Sundaram',
      students: ['Kavitha R', 'Srinivasan P', 'Deepak Raja'],
      solutionSummary:
        'Detailed layout overhaul replacing dangerous wiring with modular distribution panels, installing ergonomically designed chemical-resistant workstation tops, and supplying 10 reconditioned thin-client PCs with open-source Virtual Science Lab software.',
      documentName: 'PSG_GovtSchool_Lab_Restoration_Blueprint.pdf',
      documentSize: '4.8 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1003',
    title: 'Streetlights Not Functioning along 4km Bypass Corridor',
    category: 'Street Lighting',
    location: 'Perundurai West Bypass, Erode District, Tamil Nadu',
    pincode: '638052',
    description:
      'Total lighting failure across 48 sodium lamp posts due to aging underground cables. The dark stretch has seen 14 road accidents and poses serious safety risks for evening factory commuters and female workers.',
    votes: 2134,
    severity: 'Medium',
    researchStatus: 'Not Required',
    totalFundingRequired: 30000,
    currentFunding: 5000,
    deadline: new Date(now + days(12) + hours(10)).toISOString(),
    status: 'Active',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1004',
    title: 'Severe Stormwater Drain Inundation & Urban Flooding',
    category: 'Stormwater',
    location: 'Singanallur Lake Canal Zone, Coimbatore, Tamil Nadu',
    pincode: '641005',
    description:
      'Choked drainage channels and unlined masonry culverts lead to 2-foot sewage overflow during heavy rain, inundating 4,500 residences and breeding vector-borne diseases like dengue.',
    votes: 12890,
    severity: 'Critical',
    researchStatus: 'Completed',
    totalFundingRequired: 500000,
    currentFunding: 240000,
    deadline: new Date(now + days(3) + hours(2)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'Coimbatore Institute of Technology (CIT)',
      department: 'Civil & Hydro-Informatics Research Wing',
      studentTeam: 'HydroShield CIT',
      mentor: 'Dr. V. Rajeshwari',
      students: ['Manoj Kumar', 'Sneha M', 'Vikram B', 'Gokul Nath'],
      solutionSummary:
        'Hydro-dynamic simulation using GIS modeling to redesign the bottleneck culverts with automated trash-rack interceptors and bio-swale percolation ponds along canal banks.',
      documentName: 'CIT_Stormwater_Desiltation_Modeling.pdf',
      documentSize: '6.1 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1005',
    title: 'Illegal Solid Waste Accumulation & Open Garbage Burning',
    category: 'Waste Management',
    location: 'Moolapalayam Ward 18, Erode Municipality, Tamil Nadu',
    pincode: '638002',
    description:
      'Over 8 tonnes of mixed unsegregated waste is dumped daily on open municipal land adjacent to residential colonies, leading to continuous toxic smoldering fires and respiratory ailments.',
    votes: 5782,
    severity: 'High',
    researchStatus: 'Not Required',
    totalFundingRequired: 50000,
    currentFunding: 18000,
    deadline: new Date(now + days(6) + hours(18)).toISOString(),
    status: 'Active',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1006',
    title: 'Restoration & Bio-Remediation of Contaminated Village Pond',
    category: 'Lakes & Water Bodies',
    location: 'Othakadai Village, Madurai District, Tamil Nadu',
    pincode: '625107',
    description:
      'Historic 4-acre community pond choked with invasive water hyacinth, plastics, and domestic greywater discharge. Water table in surrounding farm wells dropped drastically due to siltation.',
    votes: 9340,
    severity: 'High',
    researchStatus: 'Completed',
    totalFundingRequired: 150000,
    currentFunding: 135000,
    deadline: new Date(now + hours(8)).toISOString(), // Deadline approaching!
    status: 'Almost Funded',
    universitySolution: {
      university: 'Thiagarajar College of Engineering',
      department: 'Centre for Water Resources & Biotechnology',
      studentTeam: 'EcoRestorers TCE',
      mentor: 'Dr. K. Swaminathan',
      students: ['Karthik Raja', 'Priya Dharshini', 'Suresh Kumar'],
      solutionSummary:
        'Constructed wetland bio-filter beds incorporating Canna indica plants, floating vetiver islands, and mechanical de-siltation to naturally treat 50 KL/day incoming runoff.',
      documentName: 'TCE_Othakadai_Pond_Remediation.pdf',
      documentSize: '5.2 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1007',
    title: 'Lack of Basic ICU Equipment in Taluk Government Hospital',
    category: 'Government Hospitals',
    location: 'Valparai Hill Taluk, Coimbatore District, Tamil Nadu',
    pincode: '642127',
    description:
      'Isolated mountain hospital servicing tea plantation workers lacks multi-para patient monitors, pediatric ventilators, and automated defibrillators, requiring critical patients to travel 65 km across hairpin bends to Coimbatore.',
    votes: 11450,
    severity: 'Critical',
    researchStatus: 'Completed',
    totalFundingRequired: 300000,
    currentFunding: 216000,
    deadline: new Date(now + days(4) + hours(11)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'Government Technology College (GCT), Coimbatore',
      department: 'Biomedical & Instrumentation Engineering',
      studentTeam: 'MedTech GCT',
      mentor: 'Dr. N. Murali Krishnan',
      students: ['Anitha V', 'Ganesh Moorthy', 'Sangeetha R'],
      solutionSummary:
        'Technical assessment and procurement specification for ruggedized, high-altitude resilient multi-parameter monitoring units with solar battery backup for continuous emergency care.',
      documentName: 'GCT_Valparai_Hospital_Equipment_Audit.pdf',
      documentSize: '2.9 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1008',
    title: 'Unsafe Damaged Culvert Bridge on School Bus Route',
    category: 'Road Safety',
    location: 'Kunnathur Panchayat, Tiruppur District, Tamil Nadu',
    pincode: '638103',
    description:
      'A 30-year-old narrow slab culvert over a irrigation canal has cracked side guardwalls and structural subsidence. Daily, 12 school buses and over 400 two-wheelers cross this high-risk point.',
    votes: 3890,
    severity: 'High',
    researchStatus: 'Not Required',
    totalFundingRequired: 120000,
    currentFunding: 120000,
    deadline: new Date(now - hours(12)).toISOString(), // Deadline passed, fully funded!
    status: 'Fully Funded',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1009',
    title: 'Public Toilet Infrastructure Collapse & Hygiene Crisis',
    category: 'Public Toilets',
    location: 'Salem Old Bus Stand Market Complex, Tamil Nadu',
    pincode: '636001',
    description:
      'The public toilet block used by 2,000 daily market vendors and commuters has broken water supply lines, damaged septic tanks, and no handwashing facilities.',
    votes: 6120,
    severity: 'High',
    researchStatus: 'Completed',
    totalFundingRequired: 80000,
    currentFunding: 15000,
    deadline: new Date(now + days(10) + hours(5)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'Government College of Engineering, Salem',
      department: 'Civil Engineering Department',
      studentTeam: 'CleanSanitation Salem',
      mentor: 'Prof. R. Saravanan',
      students: ['Muthu Kumar', 'Divya Bharathi', 'Saravanan T'],
      solutionSummary:
        'Complete overhaul including touchless sensor taps, dual-flush greywater recycling system, exhaust ventilation hoods, and an automated coin-free smart turnstile entry system.',
      documentName: 'GCE_Salem_Public_Sanitation_DPR.pdf',
      documentSize: '4.1 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1010',
    title: 'Lack of Solar Power Backup for Rural Primary Health Centre',
    category: 'Healthcare',
    location: 'Bhavanisagar Forest Fringe PHC, Erode, Tamil Nadu',
    pincode: '638451',
    description:
      'Frequent 6-hour power outages disrupt vaccine cold-chain refrigeration (antivenom and rabies vaccines) and emergency childbirth procedures at night.',
    votes: 7520,
    severity: 'Critical',
    researchStatus: 'Completed',
    totalFundingRequired: 90000,
    currentFunding: 86400, // 96% funded
    deadline: new Date(now + hours(4) + minutes(30)).toISOString(), // 4h remaining!
    status: 'Almost Funded',
    universitySolution: {
      university: 'Bannari Amman Institute of Technology (BIT)',
      department: 'Department of Electrical & Electronics Engineering',
      studentTeam: 'SolarMed BIT',
      mentor: 'Dr. P. Thangaraj',
      students: ['Siddharth S', 'Lavanya K', 'Naveen Kumar'],
      solutionSummary:
        'Design of a 5kW rooftop hybrid solar PV system with Lithium Iron Phosphate (LiFePO4) battery backup and GSM-enabled remote monitoring for continuous cold-chain tracking.',
      documentName: 'BIT_PHC_Solar_Backup_Design.pdf',
      documentSize: '3.8 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1011',
    title: 'Erosion of Coastal Footpath & Protection Wall Failure',
    category: 'Coastal Infrastructure',
    location: 'Neelankarai Beach Stretch, Chennai, Tamil Nadu',
    pincode: '600115',
    description:
      'High wave action during monsoons collapsed 180 metres of coastal pedestrian footpath and sea wall, endangering coastal fisherman settlements and public beachgoers.',
    votes: 4900,
    severity: 'Medium',
    researchStatus: 'Completed',
    totalFundingRequired: 220000,
    currentFunding: 0, // 0% funded example
    deadline: new Date(now + days(14)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'Anna University (CEG Campus), Chennai',
      department: 'Department of Ocean Engineering',
      studentTeam: 'CoastalGuard Anna Univ',
      mentor: 'Dr. M. Senthil Kumar',
      students: ['Akash Chandran', 'Bhavana M', 'Rajesh Kannan'],
      solutionSummary:
        'Interlocking geo-bag embankment with native mangrove/Ipomea vegetation matrix to dissipate wave energy naturally while restoring the pedestrian walkway.',
      documentName: 'AnnaUniv_Coastal_Erosion_Shield.pdf',
      documentSize: '7.4 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1012',
    title: 'Broken Solar Micro-Grid in Remote Tribal Village',
    category: 'Rural Infrastructure',
    location: 'Kadambur Hills, Sathyamangalam, Tamil Nadu',
    pincode: '638503',
    description:
      'A 12-family tribal hamlet isolated inside the tiger reserve has been in darkness for 8 months after lightning struck their centralized solar inverter.',
    votes: 3410,
    severity: 'High',
    researchStatus: 'Not Required',
    totalFundingRequired: 45000,
    currentFunding: 10000,
    deadline: new Date(now + days(7) + hours(12)).toISOString(),
    status: 'Active',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1013',
    title: 'Smart Flood Early Warning System for Riverbank Settlement',
    category: 'Disaster Management',
    location: 'Bhavani River Basin, Gobichettipalayam, Tamil Nadu',
    pincode: '638452',
    description:
      'Sudden dam water releases cause unexpected flash inundation in low-lying riverside communities. Lack of localized sirens leads to livestock loss and evacuation chaos.',
    votes: 8910,
    severity: 'Critical',
    researchStatus: 'Completed',
    totalFundingRequired: 160000,
    currentFunding: 112000,
    deadline: new Date(now + days(2) + hours(15)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'Kumaraguru College of Technology (KCT)',
      department: 'Mechatronics & Embedded Systems Lab',
      studentTeam: 'FloodAlert KCT',
      mentor: 'Dr. S. Bhaskar',
      students: ['Hariharan P', 'Kavya S', 'Rohan Verma', 'Nitin G'],
      solutionSummary:
        'Ultrasonic water level sensor nodes deployed along river bends that transmit real-time telemetry over LoRaWAN to solar-powered village sirens and emergency WhatsApp broadcast groups.',
      documentName: 'KCT_Flood_Early_Warning_Architecture.pdf',
      documentSize: '5.6 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1014',
    title: 'Silt Accumulation & Irrigation Channel Blockage',
    category: 'Irrigation',
    location: 'Amravathi Basin, Dharapuram, Tamil Nadu',
    pincode: '638656',
    description:
      'Over 12 km of primary agricultural feeder canal is heavily silted and choked with prosopis juliflora bushes, depriving 450 small farmers of tail-end irrigation water.',
    votes: 6730,
    severity: 'High',
    researchStatus: 'Not Required',
    totalFundingRequired: 180000,
    currentFunding: 90000,
    deadline: new Date(now + days(11)).toISOString(),
    status: 'Active',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1015',
    title: 'Public Park Infrastructure Renovation for Senior Citizens & Children',
    category: 'Public Parks',
    location: 'R.S. Puram Ward 23, Coimbatore, Tamil Nadu',
    pincode: '641002',
    description:
      'Broken play equipment, lack of wheelchair-accessible walkways, broken benches, and non-functional lighting have turned a 1-acre public park into a neglected area.',
    votes: 3120,
    severity: 'Low',
    researchStatus: 'Not Required',
    totalFundingRequired: 40000,
    currentFunding: 40000,
    deadline: new Date(now - days(2)).toISOString(),
    status: 'Fully Funded',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1016',
    title: 'High Air Pollution & Particulate Matter at Industrial Traffic Junction',
    category: 'Air Quality',
    location: 'SIDCO Industrial Estate Crossing, Kurichi, Coimbatore',
    pincode: '641021',
    description:
      'Heavy truck traffic and foundry emissions cause severe PM2.5 levels (> 220 µg/m³), affecting thousands of industrial workers and nearby residents.',
    votes: 7890,
    severity: 'High',
    researchStatus: 'Completed',
    totalFundingRequired: 210000,
    currentFunding: 147000,
    deadline: new Date(now + days(6) + hours(4)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'Coimbatore Institute of Technology (CIT)',
      department: 'Department of Chemical Engineering',
      studentTeam: 'CleanAir CIT',
      mentor: 'Dr. C. Amritha',
      students: ['Vidyasagar R', 'Swathi K', 'Archana S'],
      solutionSummary:
        'Outdoor IoT smog-tower unit equipped with electrostatic precipitator panels and automated misting nozzles that trigger when PM2.5 exceeds safe limits.',
      documentName: 'CIT_Urban_SmogTower_Design.pdf',
      documentSize: '4.5 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1017',
    title: 'Lack of Disabled-Friendly Tactile Footpaths near Railway Station',
    category: 'Accessibility',
    location: 'Tiruppur Railway Station North Entrance, Tamil Nadu',
    pincode: '641601',
    description:
      'High pedestrian footfall area lacks wheelchair ramps, tactile paving tiles for visually impaired travelers, and safe audio pedestrian signals at busy crosswalks.',
    votes: 4150,
    severity: 'Medium',
    researchStatus: 'Completed',
    totalFundingRequired: 65000,
    currentFunding: 65000,
    deadline: new Date(now - hours(48)).toISOString(),
    status: 'Fully Funded',
    universitySolution: {
      university: 'Kongu Engineering College',
      department: 'Civil Engineering & Infrastructure Planning',
      studentTeam: 'AccessForAll KEC',
      mentor: 'Prof. T. Ramakrishnan',
      students: ['Deepika M', 'Senthil Nathan', 'Vishnu Prasad'],
      solutionSummary:
        'Designed standard IRC-compliant tactile footpath layout with curb ramps, bollard barriers to prevent motorcycle intrusion, and smart auditory zebra signals.',
      documentName: 'KEC_Accessible_Footpath_Blueprint.pdf',
      documentSize: '3.1 MB',
      verifiedByGovt: true,
    },
  },
  {
    id: 'SETU-PRB-1018',
    title: 'Sewage Overflow & Pipeline Degradation in Dense Residential Colony',
    category: 'Sewage',
    location: 'Hasthampatti Main Ward, Salem, Tamil Nadu',
    pincode: '636007',
    description:
      'Corroded concrete sewage pipe collapsed underground, causing raw sewage backflow into groundwater wells and open streets across 3 lanes.',
    votes: 6490,
    severity: 'Critical',
    researchStatus: 'Not Required',
    totalFundingRequired: 140000,
    currentFunding: 42000,
    deadline: new Date(now + days(4) + hours(19)).toISOString(),
    status: 'Active',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1019',
    title: 'Roof Leakage & Electrical Danger in Government Anganwadi Centre',
    category: 'Government Schools',
    location: 'Thuckalay Panchayat, Kanyakumari District, Tamil Nadu',
    pincode: '629175',
    description:
      'Anganwadi catering to 35 toddlers aged 2-5 has roof concrete spalling during monsoon, exposing rusty rebar and soaked electrical switches.',
    votes: 5210,
    severity: 'High',
    researchStatus: 'Not Required',
    totalFundingRequired: 35000,
    currentFunding: 35000,
    deadline: new Date(now - days(5)).toISOString(),
    status: 'Funding Closed',
    universitySolution: null,
  },
  {
    id: 'SETU-PRB-1020',
    title: 'High Noise Pollution & Traffic Congestion near Maternity Hospital Zone',
    category: 'Noise Pollution',
    location: 'Government Maternity Hospital Gate, Dindigul, Tamil Nadu',
    pincode: '624001',
    description:
      'Continuous blaring horns from heavy state transport buses and commercial vans at hospital entrance exceed 85 dB, disturbing newborn care and post-operative recovery.',
    votes: 3820,
    severity: 'Medium',
    researchStatus: 'Completed',
    totalFundingRequired: 55000,
    currentFunding: 18000,
    deadline: new Date(now + days(9) + hours(8)).toISOString(),
    status: 'Active',
    universitySolution: {
      university: 'PSNA College of Engineering & Technology, Dindigul',
      department: 'Department of Electronics & Communication Engineering',
      studentTeam: 'QuietZone PSNA',
      mentor: 'Dr. G. Kannan',
      students: ['Subash C', 'Reshma Banu', 'Vigneshwaran K'],
      solutionSummary:
        'Acoustic camera monitoring coupled with automatic license plate recognition (ANPR) and automated LED horn warning displays to enforce silence zones.',
      documentName: 'PSNA_Hospital_Acoustic_Shield_DPR.pdf',
      documentSize: '3.6 MB',
      verifiedByGovt: true,
    },
  },
]

// Historical Contributions for ArunTech Industries / CSR Partner
export const HISTORICAL_CONTRIBUTIONS = [
  {
    id: 'SETU-HIST-801',
    problemId: 'SETU-PRB-1008',
    problemTitle: 'Unsafe Damaged Culvert Bridge on School Bus Route',
    category: 'Road Safety',
    location: 'Kunnathur Panchayat, Tiruppur District',
    fundingDate: '18 August 2026',
    companyContribution: 50000,
    totalFunding: 120000,
    finalStatus: 'Funding Completed',
    impactSummary: 'Successfully reconstructed structural concrete culvert and safety guardrails, securing travel for 12 school buses daily.',
    universityName: 'N/A (Direct Municipal Execution)',
  },
  {
    id: 'SETU-HIST-802',
    problemId: 'SETU-PRB-1015',
    problemTitle: 'Public Park Infrastructure Renovation for Senior Citizens',
    category: 'Public Parks',
    location: 'R.S. Puram Ward 23, Coimbatore',
    fundingDate: '04 August 2026',
    companyContribution: 25000,
    totalFunding: 40000,
    finalStatus: 'Funding Completed',
    impactSummary: 'Installed senior citizen benches, wheelchair ramps, and solar garden lighting.',
    universityName: 'N/A',
  },
  {
    id: 'SETU-HIST-803',
    problemId: 'SETU-PRB-1017',
    problemTitle: 'Lack of Disabled-Friendly Tactile Footpaths near Railway Station',
    category: 'Accessibility',
    location: 'Tiruppur Railway Station North Entrance',
    fundingDate: '22 July 2026',
    companyContribution: 65000,
    totalFunding: 65000,
    finalStatus: 'Funding Completed',
    impactSummary: 'Full 100% funding provided by ArunTech Industries. Tactile paving installation completed by Kongu Engineering Team.',
    universityName: 'Kongu Engineering College',
  },
  {
    id: 'SETU-HIST-804',
    problemId: 'SETU-PRB-1099',
    problemTitle: 'Solar Power Installation for Rural Anganwadi Centre',
    category: 'Government Schools',
    location: 'Vellakoil Village, Tiruppur District',
    fundingDate: '15 June 2026',
    companyContribution: 75000,
    totalFunding: 75000,
    finalStatus: 'Funding Completed',
    impactSummary: '2kW solar PV skid supplying 24/7 power for fan, lights, and milk heater.',
    universityName: 'PSG College of Technology',
  },
  {
    id: 'SETU-HIST-805',
    problemId: 'SETU-PRB-1098',
    problemTitle: 'Deep Borewell Desalination Unit for Tribal Residential Hostel',
    category: 'Drinking Water',
    location: 'Anaimalai Hills, Coimbatore',
    fundingDate: '02 May 2026',
    companyContribution: 150000,
    totalFunding: 180000,
    finalStatus: 'Completed',
    impactSummary: 'Clean drinking water provided to 140 resident tribal students.',
    universityName: 'Government Technology College (GCT)',
  },
  {
    id: 'SETU-HIST-806',
    problemId: 'SETU-PRB-1097',
    problemTitle: 'Automated Water Quality Telemetry in Noyyal River Basin',
    category: 'Lakes & Water Bodies',
    location: 'Noyyal Basin, Tiruppur',
    fundingDate: '18 March 2026',
    companyContribution: 200000,
    totalFunding: 250000,
    finalStatus: 'Completed',
    impactSummary: 'Deployed 6 online pH/TDS monitoring probes reporting data to Pollution Control Board.',
    universityName: 'Coimbatore Institute of Technology (CIT)',
  },
]
